nhsuk/nhsuk-service-manual

- package-lock.json
- package.json
Azure devops requires the gulp-cli dependency because of an issue
with it, this issue is being worked on by Microsoft but in the
meantime we'll need this dependency.
> Temporarily install gulp-cli as a project dependency

- azure-pipelines.yml
This is an alternative for not publishing e.g. the .git file, that doesn't require rearranging the repository up-front.
> Move repository into desired state during build

- app/components/grid.njk
- app/styles/design-example-overrides.scss
- app/views/includes/design-example-wrapper.njk
- Move nhsuk-frontend library overrides into it's own .scss file.
Any styles that affect the code examples should go into the `design-example-override.scss` file.
This file is only served in the code examples and not the rest of the service manual, so it will help us 
isolate any code that makes examples look different to the "vanilla" frontend library.
- Add some CSS to make the grid example visible. (blue-box styles taken from the old service manual)
> Make the grid examples visible

- app/views/index.njk
There was extra padding on mobile devices around the Community and Contribute sections of the Service Manual homepage. This was caused by an extra `nhsuk-width-container` being used, there is already a `nhsuk-width-container` wrapping the page around the `<main>` element.
```
<div class="nhsuk-width-container">
<main class="nhsuk-main-wrapper" id="maincontent">
</main>
</div>
```
> Remove extra nhsuk-width-container causing extra padding on mobile

- app/scripts/main.js
- app/scripts/polyfills.js
We had javascript errors due to lack of `forEach` support on `NodeList` objects, which meant that the code snippet button wasn't working. This polyfill adds `forEach` support.
> Add an IE11 polyfill for forEach on nodelists

- app/views/frontend-library.njk
The link was incorrect for the NHS.UK contributing documentation, this link is the correct link.
> Link to the NHS.UK frontend contributing docs

- app.js
- app/views/includes/design-example.njk
- app/views/includes/header.njk
- app/views/page-not-found.njk
Links to the homepage should be `/service-manual` otherwise when we deploy to https://beta.nhs.uk `/` would link to the beta homepage rather than the service manual homepage.
> Fix the broken homepage links for deployment to beta

- app/views/includes/layout.njk
Local image paths don't work for the social media image cards, the path needs to be the full URL.
> Use full URL for the social media image cards

- app/views/styles-components-patterns/breadcrumbs.njk
The link from 'breadcrumbs' to 'footer' worked locally, but had a typo and didn't work in the live site.
> Fix link from 'breadcrumbs' to 'footer'

- app/views/includes/design-example.njk
Using caret icon to convey close does not follow our icon guidelines.
> Remove the caret icon for close snippet

- app.js
The "page not found" page is being served as a valid http response (200 OK). It now returns a 404 status code.
> [refs #117] Set status code 404 on page not found pages

- azure-pipelines.terraform.yml
- azure-pipelines.yml
This should make it so that terraform changes do a new terraform plan / apply, but non-terraform changes don't.
> Split out terraform build from standard pipelines build.

- CHANGELOG.md
- app/views/styles-components-patterns/draft/mini-hub.njk
- app/views/styles-components-patterns/index.njk
The Mini-Hub pattern still needs to be removed so isn't ready to be released.
> move mini-hub pattern to drafts and remove links to page

- app/views/styles-components-patterns/header.njk
- app/views/styles-components-patterns/radios.njk
- app/views/styles-components-patterns/table.njk
Remove table with panel from body of table page but refer to it in research.
Make it clearer when to use header for transactions or non-NHS.UK services.
Tweak radio page.
> Update component pages

- CHANGELOG.md
- package-lock.json
- package.json
- Accessibility guidance pages grammar and content updates
- Add 'homeless' to the A-Z of NHS health writing
- Add external links to the links and PDF guidance pages
> update package dependencies to latest versions

- app/views/design-principles/index.njk
Make apostrophe straight in principle 4 of design principles
> Correct apostrophe in design-principles/index.njk to match style guide

- CHANGELOG.md
- app/views/includes/header.njk
The home link in the header was labelled as 'NHS homepage', causing confusion for users using screenreaders.
The aria label has been updated to 'NHS Digital service manual homepage'
> Accessibility: updated header home link aria label

- CHANGELOG.md
- app.js
- app/views/accessibility/how-to-make-digital-services-accessible.njk
- app/views/accessibility/partials/look-after-your-team.njk
- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/content/how-we-write.njk
- app/views/content/index.njk
- app/views/design-principles/index.njk
- app/views/includes/header.njk
- app/views/includes/layout.njk
- app/views/includes/search.njk
- app/views/sitemap.xml
- app/views/styles-components-patterns/care-cards.njk
- package-lock.json
- package.json
:new: **New content**
- Add entries to A to Z of NHS health writing: health record and related terms
- Remove duplicate entry from the XML sitemap
- Accessibility: Updated home link aria label, it now reads as "NHS digital service manual homepage"
- Fix a few minor content formatting issues, like apostrophes
> Release 1.8.0

- app/views/content/inclusive-language.njk
#139 updated the H2 to now read 'Sex, gender and sexuality' instead of 'Gender and sexuality'
> Update the inclusive language page

- azure-pipelines.terraform.yml
- deploy/terraform/backend.tf
- deploy/terraform/init.sh
As part of Brexit repatriation, the storage account tfbackends moved to UK South. As part of the move, it has changed resource group to tfbackends-uks, and the group tfbackends no longer contains the tfbackends storage account.
> Update tfbackends resource group to tfbackends-uks.

- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/content/inclusive-language.njk
Add mini-hub pattern at top of Inclusive language page
Change how we refer to baby in Inclusive language page and link to word "baby" in A to Z of NHS health writing
Add entries for "baby" and "foetus" to A to Z
Add words "drowsy", "sleepy" and "sedating" to the A to Z 
Update entry for "summary care record" in A to Z to cover use of abbreviation
Add new term "preconception care" to A to Z
Add term "seizure or fit" to A to Z with a link from "fit" to "seizure or fit"
Update dates on Inclusive language and A to Z pages to September 2019
> Update 2 pages after last Style Council meeting

- CHANGELOG.md
- package-lock.json
- package.json
- Use the latest version of the NHS.UK frontend library (v2.3.1)
> Update to latest version of NHS.UK frontend and dependencies

- app/views/content/how-to-write-good-questions/2-make-sure-you-need-each-question.njk
- app/views/content/how-to-write-good-questions/3-consider-the-sensitivities-around-your-questions.njk
Mentioned GDPR (Ian's comment)
Cut out the mantra.
Put "Understand why you're asking the question first" - the protocol - then "Only ask for info you need". (The latter is now more prominent than it was, but I don't think it should come ahead of the protocol.)
Created a new page on sensitive questions - I still need to update the nav and linking across the guidance.
> Update needing each question and add new sensitivities page

- app/views/content/how-to-write-good-questions-for-forms/consider-the-sensitivities-around-your-questions.njk
- app/views/content/how-to-write-good-questions-for-forms/index.njk
- app/views/content/how-to-write-good-questions-for-forms/use-yes-no-questions-but-be-careful.njk
- app/views/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form.njk
- app/views/styles-components-patterns/confirmation-page.njk
- app/views/styles-components-patterns/error-message.njk
- app/views/styles-components-patterns/start-page.njk
Iterate start page, errors page, and confirmation page
Add help text to NHS number on supporting content page - hint text still needs line break
Added example of another way on Yes No page
Uppercased GOV.UK Design System throughout.
> Iterate component pages for good questions guidance

- CHANGELOG.md
- app/config.js
- app/locals.js
- app/views/includes/design-example-wrapper-full.njk
- app/views/includes/design-example-wrapper.njk
- app/views/includes/layout.njk
- app/views/includes/template.njk
- package-lock.json
- package.json
- webpack.config.js
Akamai firewall caches our CSS for longer than our HTML, so often latest styles don't come in till hours later. Hopefully this way we will bust the cache to see our new styles quicker.
> cache bust CSS and JavaScript by outputting version numbers

- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/includes/_footer.njk
- app/views/whats-new/blog-posts.njk
- app/views/whats-new/index.njk
- app/views/whats-new/show-and-tells.njk
- app/views/whats-new/updates.njk
Add 2 more blog posts and info about upcoming show and tell.
Push accessibility to front of footer.
Amend wording re acute, chronic, kidney and renal in A to Z of NHS writing after Style Council meeting.
> Update What's new, footer and A to Z

- CHANGELOG.md
- app/views/cookie-policy.njk
- app/views/whats-new/index.njk
- app/views/whats-new/show-and-tells.njk
- package-lock.json
- package.json
- Use the no cookie version of YouTube video embedding
- Remove unused cookie (ARRAffinity) from the cookie policy page as we no longer set this cookie
> Fix YouTube cookies and remove unused cookie from policy page

- CHANGELOG.md
- app/views/community/backlog-of-components-and-patterns.njk
- package.json
Add the print this page issue to the [backlog of components and patterns](http://localhost:3000/community/backlog-of-components-and-patterns) page
Print this page - service manual backlog [issue #240](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/240)
> Add "print this page" issue to community backlog of components and patterns

- CHANGELOG.md
- app/views/design-system/styles/layout.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Add guidance for the `<main>` wrapper vertical spacing modifier classes
([Community backlog Issue 221](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/221))
> add guidance for the main wrapper spacing modifier classes

- CHANGELOG.md
- app/components/a-z.njk
- package-lock.json
Fixed the A to Z page example. It wasn't using the 'full page' example code.
Before:
After:
> Fix A to Z page pattern example

- CHANGELOG.md
- app/views/design-system/components/header.njk
The paragraph underneath the "Organisational header" heading was in the H3. This makes the heading rather large, especially if screen readers navigate via headings.
None
> Separated out text from organisational header heading

- CHANGELOG.md
- app/components/layout-main.njk
- app/components/layout-one-third-container-fluid.njk
- app/components/layout-two-thirds-container.njk
- app/scripts/main.js
- app/views/includes/layout.njk
- app/views/index.njk
- package-lock.json
- package.json
The Header autocomplete was being initialised twice, this was due to the default export for the Header component initialising the autocomplete, then our autocomplete configuration in the Service manual was initialising the autocomplete again. This caused duplicate elements for the autocomplete.
Instead of initialising the whole Header, initialise them separately passing our configuration through.
Also add `role="main"` to the `<main>` container for consistency with other NHS services and fix any potential issues with accessibility on older devices/software.
> prevent the autocomplete from being initialised twice

- app/views/design-system/components/images.njk
##Description
Update date for images guidance
Link to accessibility guidance on images rather than W3C or GOV.UK
Bring "don't" and "won't" into line with content style
https://jira.service.nhs.uk/browse/STAN-1735
Not yet - I'll do changelog, what's new and update page date when I've checked it in staging.
> Amend date and link to accessibility guidance

- app/views/includes/_header-prototype.njk
- app/views/includes/_header.njk
Bug fix for search page header - adding `nhsuk-header__menu--only` class to header when search is disabled
> Add `nhsuk-header__menu--only` class to header for when search is disabled

- CHANGELOG.md
- app/styles/design-example/_code-snippet.scss
- app/styles/design-example/_design-example.scss
- app/views/design-system/components/header.njk
- app/views/design-system/components/summary-list.njk
- app/views/includes/app-layout.njk
- package.json
Removed the experimental tags from the organisational header and summary list component.
Also, updated the focus style for the design example links.
> Remove experimental tags + fix code example focus styles

- app/views/content/how-to-write-good-questions-for-forms/consider-the-sensitivities-around-your-questions.njk
- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Add phone entry in A to Z of health writing to What's new pages.
Also update forms guidance - replace telephone with phone.
> Add phone entry to What's new and update forms guidance

- app/views/design-system/components/radios.njk
There was a mistake in the guidance, it said 'checkbox' instead of 'radio'.
> Fix - swap the word  'checkbox' with 'radio'

- CHANGELOG.md
- app/components/typography-weight.njk
- app/views/design-system/styles/typography.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
https://github.com/nhsuk/nhsuk-service-manual/issues/912
> Update code example for the font weight normal override class

- app/views/includes/_footer.njk
- app/views/site-map.njk
Bring site map file into line with Style Council decision - "sitemap" should be 2 words "site map" for accessibility reasons.
[Get the site map page on the NHS and service manual sites changed #873](https://github.com/nhsuk/nhsuk-service-manual/issues/873)
> Change sitemap to site map to align with Style Council decision

- middleware/page-index.js
Following the change to the HTML site map page name, fix the site map path name in page indexer
> fix the site map path name in page indexer

- CHANGELOG.md
- app/views/accessibility/partials/use-headings-correctly.njk
- package-lock.json
- package.json
Fixed hyperlink for chrome web developer tool
#958
> Bug fix accessibility link #958

- CHANGELOG.md
- app.js
- package-lock.json
- package.json
Removed the `/index` from the community page URL redirect.
> Update `app.js` community redirect url

- CHANGELOG.md
- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/content/how-to-write-good-questions-for-forms/consider-the-sensitivities-around-your-questions.njk
- app/views/content/how-to-write-good-questions-for-forms/get-the-questions-into-order.njk
- app/views/content/how-to-write-good-questions-for-forms/index.njk
- app/views/content/how-to-write-good-questions-for-forms/make-sure-you-need-each-question.njk
- app/views/content/how-to-write-good-questions-for-forms/test-your-questions.njk
- app/views/content/how-to-write-good-questions-for-forms/think-of-the-form-as-a-conversation.njk
- app/views/content/how-to-write-good-questions-for-forms/understand-the-problem-before-you-write-your-questions.njk
- app/views/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users.njk
- app/views/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form.njk
- app/views/includes/_contact-panel.njk
- app/views/includes/app-layout.njk
This is a prototype based on improving the users access to our contribution process through the service manual website
We will use this pull request to review changes, updates et al
#1000 #1001
> Add contribution links within context #1000 #1001

- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Update the coronavirus (COVID-19) entry in our content style guide with a link to new GOV.UK coronavirus (COVID-19) A to Z.
Agreed at March 2021 Style Council meeting - one of [follow up actions](https://github.com/nhsuk/nhsuk-service-manual/issues/1064)
> Add GOV.UK coronavirus style guide to our A to Z

- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Add entry for GP system supplier names to A to Z of NHS health writing - after March Style Council.
Updated after conversation with Olivia. 
- [Follow up after March Style Council meeting](https://github.com/nhsuk/nhsuk-service-manual/issues/1064)
> Add new entry to A to Z re GP systems

- CHANGELOG.md
- app/styles/app/_example-callout.scss
- app/views/content/formatting-and-punctuation.njk
- app/views/content/how-we-write.njk
- package.json
It's confusing that the 'Example' and 'Research insight' callouts are styled the same.
Use inset text component for 'Research insights'.
I've also reverted the 'Example' tag colour back to dark grey. This was inadvertently changed when we added the tag component.
> Update content example and research insight callouts

- CHANGELOG.md
- app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk
- package-lock.json
- package.json
fix broken health literacy link on the service standard pages
fixes #1136
> [refs #1136] fix broken health literacy link on the service standard pages

- app/styles/app/_autocomplete.scss
Update the search input field placeholder colour to the darker grey to pass colour contrast levels, as per the frontend library:
https://github.com/nhsuk/nhsuk-frontend/blob/7dc973d2f5d2ae788edb9625bde72b879b4969bc/packages/components/header/_header.scss#L187
none
> Update placeholder colour to darker grey to increase colour contrast

- app/views/design-system/components/date-input/with-errors/index.njk
Where possible, I advocate using real content in examples as opposed to placeholder or indicative content. 
This PR proposes to change the error message text in the date input example to "Enter your date of birth" which:
- is appropriate for the context of the example
- follows GOV.UK Design System guidance on error messages for date inputs: https://design-system.service.gov.uk/components/date-input/
> Add real error message to example

- app/views/accessibility/partials/use-alternative-text-for-images-in-content.njk
- app/views/design-system/components/images/default/index.njk
- app/views/design-system/components/images/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
At Style Council, we agreed to bring the example image in the image component into line with the accessibility guidance example. Having 2 examples was confusing and the accessibility guidance example is the better one.
Also add more guidance about captions - agreed at Style Council
https://github.com/nhsuk/nhsuk-service-manual/issues/1231
> Change image in image component and explain captions

- app/views/get-in-touch.njk
- app/views/includes/_footer.njk
- app/views/index.njk
Add 3 links to the satisfaction survey to:
- index page
- footer
- Get in touch page
https://github.com/nhsuk/nhsuk-service-manual/issues/1309
> Add links to satisfaction survey

- .gitpod.yml
- README.md
adding Gitpod config to service manual repo - browser-based development environment
> added gitpod script and README button

- CHANGELOG.md
- app/views/design-system/components/header/index.njk
- package-lock.json
- package.json
use the correct Service Header example on the Header components page as it was using the default header twice
> use the correct Service Header example on the Header components page

- app/views/design-system/patterns/start-page/example/index.njk
Start now link should be an anchor tag styled as button so that it is semantically correct.
Also removed an empty folder.
> use anchor link instead of button for start now

- app/views/design-system/components/checkboxes/index.njk
- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Minor tweaks to content. @PeteKowalczykNHS , for info, we use straight double quotes "". 
I've also noted this change on the What's new index page, the What's new updates page and the home page, assuming that we'll publish in the next day or 2. 
Still waiting to discuss an alternative NHS example. But otherwise this content is fine.
> Make minor tweaks to content and do what's new

- app/views/design-system/components/checkboxes/none-option/index.njk
Changing the content to be about "symptoms".
> Changing example content for  "none" checkbox

- CHANGELOG.md
- app/views/design-system/components/checkboxes/conditional/index.njk
- app/views/design-system/components/checkboxes/default/index.njk
- app/views/design-system/components/checkboxes/error-messages/index.njk
- app/views/design-system/components/checkboxes/index.njk
- app/views/design-system/components/checkboxes/items-with-hints/index.njk
- app/views/design-system/components/checkboxes/macro-options.json
- app/views/design-system/components/checkboxes/none-option/index.njk
- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
- package-lock.json
- package.json
Following the addition of the logic for "None of the above" in Checkboxes, we need to add guidance to the Service Manual. This is a first draft following the GOV.UK Design System Guidance
https://github.com/nhsuk/nhsuk-frontend/pull/756
> Checkboxes add an option for none example and guidance

- app/views/design-system/components/checkboxes/hint/index.njk
- app/views/design-system/components/checkboxes/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
- Add team page and feedback survey links to What's new
- Amend link wording and destination on checkboxes page
> Update What's new and amend link on checkboxes page

- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Update What's new index page, What's new updates page and service manual home page with new care card pattern and links to it
> Update What's new

- app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/non-urgent/index.njk
Update link element in the non-urgent card cards example.
Although in normal HTML, this isn’t needed, we need to use a backwards slash before each quotation mark in the link (`a`) element here as it’s a nunjucks file.
> Update link element in the non-urgent card card example

- app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/emergency/index.njk
- app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/macro-options.json
- app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/non-urgent/index.njk
Removed links to live NHS.UK pages from the new care card pattern examples (for now)
> Fix care card example links

- CHANGELOG.md
- middleware/page-index.js
Improving the search so that the inclusion of - no longer treats the secondary word as a new word.
fixes #742
> Split lunr query on spaces only

- app/views/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Add What's new content for accessibility posters.
> Add what's new content

- app/views/content/a-to-z-of-nhs-health-writing.njk
Removal of right arrow on back to top
> remove right arrow on back to top link

- app/views/content/formatting-and-punctuation.njk
- app/views/index.njk
- app/views/service-manual-team.njk
- app/views/service-standard/1-understand-users-and-their-needs-context-health-and-care.njk
- app/views/service-standard/10-define-what-success-looks-like-and-be-open-about-how-your-service-is-performing.njk
- app/views/service-standard/11-choose-the-right-tools-and-technology.njk
- app/views/service-standard/12-make-new-source-code-open.njk
- app/views/service-standard/13-use-and-contribute-to-open-standards-common-components-and-patterns.njk
- app/views/service-standard/14-operate-a-reliable-service.njk
- app/views/service-standard/15-support-a-culture-of-care.njk
- app/views/service-standard/16-make-your-service-clinically-safe.njk
- app/views/service-standard/17-make-your-service-interoperable.njk
- app/views/service-standard/2-and-3-work-towards-solving-a-whole-problem-and-provide-a-joined-up-experience.njk
- app/views/service-standard/4-make-the-service-simple-to-use.njk
- app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk
- app/views/service-standard/6-create-a-team-that-includes-multidisciplinary-skills-and-perspectives.njk
- app/views/service-standard/7-use-agile-ways-of-working.njk
- app/views/service-standard/8-iterate-and-improve-frequently.njk
- app/views/service-standard/9-respect-and-protect-users-confidentiality-and-privacy.njk
- app/views/service-standard/about.njk
- app/views/service-standard/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
- Remove beta banner from service standard
- Add reduced service message to team page
- Fix 2 content typos on formatting and punctuation page
- Do What's New
@henocookie I've done the What's new and update page dates. Would you mind checking this, please? 
I haven't updated the changelog yet. Sorry, I forgot.
> Remove beta banner from service standard

- .gitignore
- app.js
Create redirects for the old service standards urls
> Create redirects for the old service standards urls

- app/views/whats-new/updates.njk
It was causing a 404 when navigating to the 'updates' page first.
> Added forward slash to latest entry

- app/views/index.njk
- app/views/standards-and-technology/service-standard-points/17-make-your-service-interoperable.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
- Update What's new and CHANGELOG
- Add link to NHS data standards directory to service standard point 176
- [1819](https://github.com/nhsuk/nhsuk-service-manual/issues/1819)
- [1815](https://github.com/nhsuk/nhsuk-service-manual/issues/1815)
> Update What's new and add link to service standard 17

- CHANGELOG.md
- app/views/design-system/components/character-count/index.njk
- app/views/design-system/components/tabs/index.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Review and improve content for tabs and character count components
In community backlog:
- https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/279
- https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/172
In service manual sprint backlog:
- https://github.com/nhsuk/nhsuk-service-manual/issues/1860
> Make changes to content of 2 new components

- app/views/accessibility/content.njk
- app/views/accessibility/design.njk
- app/views/accessibility/development.njk
- app/views/accessibility/how-to-make-digital-services-accessible.njk
- app/views/accessibility/partials/do-not-use-accessibility-overlays-or-widgets.njk
- app/views/accessibility/what-all-NHS-services-need-to-do.njk
- app/views/design-system/styles/typography/index.njk
- app/views/index.njk
- app/views/service-manual-team.njk
- app/views/standards-and-technology/about-the-service-standard.njk
- app/views/standards-and-technology/service-standard-points/17-make-your-service-interoperable.njk
- app/views/standards-and-technology/service-standard-points/5-make-sure-everyone-can-use-the-service.njk
- app/views/terms-and-conditions.njk
- app/views/your-privacy.njk
- Add links to accessibility checklist plus new section on accessibility widgets plus new section for teams under tight deadlines - DRAFT
- Change references to NHSD so they refer to NHSE instead
- Add mentions of NHS Constitution in service standard
- https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/449
- https://github.com/nhsuk/nhsuk-service-manual/issues/1863
- https://github.com/nhsuk/nhsuk-service-manual/issues/1854
> Add draft accessibility updates, change NHSD to NHSE 

- CHANGELOG.md
- app/scripts/main.js
- package-lock.json
- package.json
Import and initialise error summary JS and set focusOnPageLoad to false so that the Error Summary examples work as expected.
Resolves NHSUK Frontend Issue [#766](https://github.com/nhsuk/nhsuk-frontend/issues/766).
> Import and initialise error summary JS and set focusOnPageLoad to false

- azure-pipelines.yml
- owasp-suppressions.xml
- package-lock.json
- package.json
Add dependency-check task in Azure build pipeline to fail anything with a score over CVE 8. Important to note that this change ignores all dev node_modules dependencies.
[Jira Ticket](https://nhsd-jira.digital.nhs.uk/browse/TM-2550)
> Add Owasp dependency scanner in azure build pipeline

- app/styles/app/_container.scss
The header and footer in the service manual is too narrow when on desktop.
> Increase max width for header and footer

- CHANGELOG.md
- app/views/content/numbers-measurements-dates-time.njk
The Standard for creating health content link doesn't currently appear at the top of the Numbers section: https://service-manual.nhs.uk/content/numbers-measurements-dates-time.
> Add link for Standard for creating health content

- CHANGELOG.md
- app/styles/main.scss
- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/design-system/patterns/a-to-z-page/default/index.njk
- app/views/design-system/patterns/a-to-z-page/index.njk
- app/views/design-system/patterns/a-to-z-page/navigation/index.njk
Issue with the Target Size for the links in the A to Z navigation section, particularly when viewed on a mobile device. The issue is around the letters "I" and "J", both of which have a narrower width than other letters. This means that there is not the 24px spacing between these links that is required for the Target Size criteria in WCAG 2.2.
> 2.5.8 criteria "Target Size (Minimum)" for AA level

- CHANGELOG.md
- app/views/content/a-to-z-of-nhs-health-writing.njk
- app/views/design-system/components/contents-list/default/index.njk
- app/views/design-system/patterns/a-to-z-page/index.njk
The links in the contents list design example were causing errors when clicked on in [this page](https://service-manual.nhs.uk/design-system/components/contents-list). These have been removed.
> Remove embedded link from contents list

- app/views/design-system/prototyping.njk
The line this refers to starts with a `{` but this wasn’t included.
It needs to be escaped with `{% raw %}` to avoid being interpreted by Nunjucks.
> Add curly brace to prototyping guidance

- app/views/includes/design-example.njk
This more accurately describes what the link does, now that most browsers have tabs.
Also follows the convention set by the GOV.UK Design System.
> Change 'open in new window' to 'a new tab'

- app/styles/design-example/govuk/_syntax-highlighting.scss
Dig report, flags issue of low contrast for some colours used in code examples: https://alpha.hugr.app/view/7e2117#DIG601
Change colour scheme of code examples used in the design system, as it currently doesn't pass WCAG minimum contrast of 4.5. 
> Tm 3171 code colour contrast

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- app/views/accessibility/partials/make-your-research-more-accessible-on-the-day.njk
- app/views/community-and-contribution/contribution-criteria.njk
- app/views/design-system/components/buttons/index.njk
- app/views/design-system/production.njk
- app/views/design-system/styles/focus-state/index.njk
- app/views/design-system/styles/icons/index.njk
- app/views/standards-and-technology/service-standard-points/4-make-the-service-simple-to-use.njk
In the `nhsuk-frontend` and `govdesign` repositories, `master` has been renamed to `main`.
(The URLs were redirecting, but updating the links avoids a banner appearing)
> Update GitHub links

- app/views/accessibility/partials/use-tables-to-show-relationships-between-data.njk
- app/views/cookie-policy.njk
A recent accessibility audit raised an issue with some of our tables, flagging that their content overflows and runs out of the viewport.
This PR addresses this by refactoring some of the tables in the service manual to make use of the responsive table styles from nhsuk-frontend.
Jira ticket: https://nhsd-jira.digital.nhs.uk/browse/TM-3174
> TM-3174 responsive tables

- app/views/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users.njk
- app/views/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form.njk
- app/views/design-system/components/hint-text/radios/index.njk
- app/views/design-system/components/radios/with-hints/index.njk
- app/views/design-system/patterns/ask-users-for-their-nhs-number/filter-third/index.njk
- app/views/design-system/patterns/ask-users-for-their-nhs-number/filter/index.njk
The existing [radio with hint example](https://service-manual.nhs.uk/design-system/components/radios#radios-with-hints) uses `call` with Fieldset, which I think is an older pattern for using this component. By using it this way, the hint doesn't get semantically linked with the fieldset as it should. It also uses two separate divs for each line of the hint, which isn't the markup I would have expected.
This updates the example in all the places it exists to follow all the other radio examples.
I think there's a wider question of whether this hint is a bit long for an example, but for now I think it's better to update the macro so the correct markup for hints is shown.
Fixes #1962
> Update radio with hint example to call fieldset correctly from radios

- app/views/design-system/components/breadcrumbs/macro-options.json
this updates the Nunjucks documentation for Breadcrumbs to clarify that the top-level `text` and `href` params should be used for the parent page, and not the current page. 
This is because, as the guidance says, "You don't need to show the current page in the breadcrumb because this information is in the H1."
If you do not include the parent page as top-level params, but instead only within the `items` array, the result is identical on desktop views, but on mobile views will result in a back arrow but no text, and an empty link with the hidden text "Back to".
> Clarify breadcrumb params

- app/views/includes/_side-nav.njk
Fixes #1971
| Before | After|
|--------|-----|
| <img width="285" alt="Screenshot showing Checkboxes before Character count" src="https://github.com/nhsuk/nhsuk-service-manual/assets/30665/a16b339d-fc4d-4f3f-8d7b-09baea5eecfa"> | <img width="307" alt="Screenshot showing Character count before Checkboxes" src="https://github.com/nhsuk/nhsuk-service-manual/assets/30665/2f49cd38-e1e1-4755-87d0-7e005597014f"> |
> Fix alphabetical order of components

- app/views/design-system/patterns/mini-hub/example/index.njk
This link is coded href="/design-example/patterns/mini-hub/example-symptoms?fullpage=true"while it should be href="#".
> Remove mini hub symptoms link

- app/views/design-system/components/summary-list/index.njk
The IDs used in the summary list headings seem to relate to another page. This updates them to match the heading text.
> Use correct IDs on summary list docs

- app/views/design-system/components/error-summary/index.njk
The guidance for errorSummary says that you need to focus the error summary on page load - but doesn't mention that the nhsuk-frontend javascript will do this for you - most services shouldn't need to do anything. Adding this text should hopefully make that clearer.
> Mention nhsuk-javascript does the focusing of the error summary

- app/scripts/design-example.js
Reverts nhsuk/nhsuk-service-manual#1968
This broke the autoresizing of the design examples. I've tested by restoring it locally and checking they now work.
> Revert "Remove unused import of 'iframeResize'"

- CHANGELOG.md
- app/views/design-system/styles/typography/headings-with-caption-inside/index.njk
- app/views/design-system/styles/typography/headings-with-caption/index.njk
- app/views/design-system/styles/typography/index.njk
Adds guidance for using headings with captions. The content is copied from GOV.UK but I've noted captions can be used below the heading (example) as well as above.
There might want to be some future work looking at the margins where it's used below the heading - but I think a good start is to document what we have and have parity with GOV.UK.
[Existing backlog issue](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/178)
> Add guidance for headings with captions

- CHANGELOG.md
- app/styles/app/_side-nav.scss
- app/views/design-system/styles/layout/index.njk
- app/views/design-system/styles/page-template/index.njk
- app/views/design-system/styles/spacing/index.njk
- app/views/design-system/styles/typography/index.njk
- app/views/includes/_side-nav.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
A mobile backlink was showing on the sidebar, even on desktop, it duplicates functionality from the breadcrumbs, so it's been removed.
| Before | After |
|--------|--------|
| ![image](https://github.com/nhsuk/nhsuk-service-manual/assets/159916913/094adcf4-a3be-419a-8f41-15bb8eefe650) | ![image](https://github.com/nhsuk/nhsuk-service-manual/assets/159916913/c91d5c32-71d4-46e6-aa82-4ecf160a23ea) |
> Removes duplicate back links in side nav on design system

- app/views/design-system/components/inset-text/default/index.njk
Use a lowercase argument for html rather than uppercase. This goes alongside [this PR](https://github.com/nhsuk/nhsuk-frontend/pull/951) on NHS Frontend (released).
> Use lowercase argument for inset text

- app/views/standards-and-technology/service-standard-points/17-make-your-service-interoperable.njk
This link now seems to redirect to a new URL, and the page has been renamed to "API and integration catalogue".
Fixes #1951
> Update API link

- app/styles/app/_container.scss
- app/views/includes/_footer.njk
- app/views/includes/_header.njk
The service manual overrides the default page width - in some cases styling existing design system classes, in some cases scoping them under app specific classes.
This causes pages to look out of alignment in the page templates section:
This adds extra scoping so the revised width is only used where an app specific class is used. This is added to the service manual header and footer, but doesn't get used by the page template examples so those now look correct.
Arguably a better solution might be for nhs-frontend to support setting the page width like GOV.UK does - that could come as a followup pr.
> Scope width overrides

- app/views/design-system/styles/colour/index.njk
`$color_nhsuk-black` is NHSUK-Frontend, but doesn't seem to be documented in the design system. I assume this is a mistake. This PR adds it in.
> Document black sass colour

- app/views/community-and-contribution/feedback-or-share-insights.njk
Replaces links to backlog project boards listed on: https://service-manual.nhs.uk/community-and-contribution/feedback-or-share-insights
New links required because of having to migrate these GitHub project boards.
> Update community backlog URLs

- app/views/design-system/components/back-link/index.njk
This updates the back link guidance to recommend that generally the back link should appear at the top-left of the page, which is what the majority of services seem to do.
It also explicitly says that it should appear before the `<main>` tag in the HTML so that the skip link will skip past it.
Previously the guidance here suggested that some services included the back link at the bottom of the content. However both of the services mentioned ([111 online](https://111.nhs.uk) and [[Choose if data from your health records is shared for research and planning](https://your-data-matters.service.nhs.uk/)](https://your-data-matters.service.nhs.uk)) seem to have since moved their back link to the top-left.
The current rationale for having the back link at the bottom is:
> That's because we don't …
> Update back link position guidance (from bottom to top)

- CHANGELOG.md
- README.md
- app.js
- app/views/accessibility/content.njk
- app/views/accessibility/design.njk
- app/views/accessibility/development.njk
- app/views/accessibility/index.njk
- app/views/accessibility/new-criteria-in-wcag-2-2.njk
- app/views/accessibility/partials/make-sure-your-service-meets-wcag-2-2.njk
- app/views/accessibility/product-and-delivery.njk
- app/views/accessibility/testing.njk
- app/views/design-system/index.njk
- app/views/includes/_side-nav.njk
- app/views/index.njk
- app/views/site-map.njk
- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
- package-lock.json
- package.json
Release 7.1.0. Includes updates to WCAG 2.2 guidance and bumps frontend to 9.0.1.
> Release 7.1.0 wcag updates

- app/views/design-system/components/checkboxes/macro-options.json
- app/views/design-system/components/radios/macro-options.json
This feature was releases as part of NHS Frontend 9.2.0 - see https://github.com/nhsuk/nhsuk-frontend/pull/1105 and I forgot to add it to the documentation in the Service Manual.
Thanks to @edwardhorsford for spotting this.
> Add description of Checkbox/Radio 'value(s)' param

- app/views/design-system/components/summary-list/index.njk
We now have a version of this within the NHS design system, so can link there instead of to the GOV.UK one.
> Update link to Complete multiple tasks pattern

- CHANGELOG.md
- app/views/design-system/styles/icons/index.njk
They are no longer provided in frontend, so this content is incorrect. And they are no longer needed, all modern browsers support SVG.
> Remove SVG fallback paragraph from icons

- CHANGELOG.md
- app/views/design-system/components/hint-text/radios/index.njk
- app/views/design-system/components/radios/with-hints/index.njk
- app/views/design-system/patterns/ask-for-nhs-numbers/filter-third/index.njk
- app/views/design-system/patterns/ask-for-nhs-numbers/filter/index.njk
- app/views/design-system/patterns/ask-for-nhs-numbers/index.njk
Bringing hint text in radio examples that mention NHS number into line with recent guidance we published re hint text. In other words, short sentences with no full stop.
This is an interim content fix, pending a full review of the NHS number pattern and NHS number-related content in coded examples.
> Update hint text in radio examples and on NHS number pattern

- app/views/whats-new/index.njk
- app/views/whats-new/updates.njk
Fix misspellings of "modifier" on What's new index and updates pages.
For next service manual release.
> Fix 2 typos 

- app/views/design-system/components/radios/with-hints/index.njk
Now that this is a single sentence, it no longer needs to use a `set` block or a margin overrride class, and can instead use the `text` param.
> Update radios hint example

- CHANGELOG.md
- app/javascripts/design-example.mjs
- app/stylesheets/app/_code-highlight.scss
- app/stylesheets/design-example/_code-embed.scss
- app/stylesheets/design-example/_code-snippet.scss
- app/views/design-system/styles/icons/arrow-right-circle/index.njk
- app/views/design-system/styles/icons/arrows/index.njk
- app/views/design-system/styles/icons/chevron-right-circle/index.njk
- app/views/design-system/styles/icons/index.njk
- app/views/design-system/styles/icons/search/index.njk
- app/views/design-system/styles/icons/sizes/index.njk
- app/views/design-system/styles/icons/tick-and-cross/index.njk
- app/views/design-system/styles/icons/user/index.njk
- app/views/macros/design-example/macro.njk
For the next breaking v10 release of NHS.UK frontend, inline SVG icons are provided to components via an `nhsukIcon` macro. This means there is now a single source of truth for our icon set, and no longer a separate store of SVG files which may fall out of sync.
This change however means we need to update our guidance page for icons. Some of the icons are no longer provided by this macro (they are provided by CSS) while links to SVG files for the remaining icons now return a 404 page. Some of the guidance is also out of date.
However, we can use the new macro in the service manual and output the same SVG code for users to copy and paste, as well as show them how they can use the macro to output icons if they are using Nunjucks.
▶️ [View updated icons …
> Update icon guidance

- app.js
- middleware/routing.js
This PR adds changes to automatically revalidate CDN-cached responses
We now use two types of default `Cache-Control` header:
1. Adds `public,max-age=0,must-revalidate` to `/assets/*` and HTML pages
2. Adds `public,max-age=2147483648,immutable` to `/javascripts/*` and `/stylesheets/*`
Where 1) is the sensible default for [Netlify's **Better Living Through Caching** approach](https://www.netlify.com/blog/2017/02/23/better-living-through-caching/)
>**“max-age=0, must-revalidate, public”** = “please cache this content, and then do not trust your cache”. This seems a bit counterintuitive, but there’s a good reason. This favors you as a content creator — you can change any of your content in an instant. Let a broken page out in a deploy? Roll back instantly. Want to make sure that your new …
> Add default cache headers

- app/views/design-system/patterns/start-page/example/index.njk
- app/views/design-system/styles/use-frutiger-font/index.njk
Switch to using the Nunjucks macro for the button on the Start page example.
This adds a missing `data-module="button"` attribute, and also helps us keep the example up to date with any HTML changes in future.
> Use Nunjucks macro for buttons

- app.js
- app/javascripts/main.mjs
- app/views/design-system/patterns/question-pages/complex-question/index.njk
- app/views/design-system/patterns/question-pages/default/index.njk
- app/views/design-system/patterns/question-pages/label-page-heading/index.njk
- app/views/design-system/patterns/question-pages/legend-page-heading/index.njk
- app/views/design-system/patterns/question-pages/multiple-questions/index.njk
When reviewing the NHS Prototype kit tutorial, @edwardhorsford and I noticed that the tutorial asks you to [copy the code from the question page examples](https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/create-pages) and then [change the action attribute in the `<form>` tag](https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/link-pages-together) to link the pages together.
However the examples don’t currently include a `<form>` tag. Whilst we could update the tutorial to mention adding this, it does feel like a helpful thing to have in the examples, especially as it also reminds you to add the `novalidate` attribute to disable any client-side validation.
This is also consistent with the [GOV.UK Design System question page …
> Add form tag to question page examples

- app/views/community-and-contribution/community-resources.njk
- app/views/design-system/components/expander/default/index.njk
Found a couple of stray `href=\""` attributes affecting the Slack sign up link etc
> Fix unnecessarily escaped HTML attributes

- app/views/design-system/components/panel/default/index.njk
- app/views/design-system/patterns/confirmation-page/default/index.njk
Updates the confirmation example to use double space indentation.
Other updates:
- Prefer `set` over inline html
- Swap panel to using `text` param
> Clean up markup for confirmation page and panel

- app/views/design-system/components/hint-text/input/index.njk
- app/views/design-system/components/hint-text/radios/index.njk
This came up in the kit training yesterday - the hint guidance for radios uses the older example we replaced a few weeks ago.
> Update hint guidance to avoid unnecessary set usage

- CHANGELOG.md
- app/views/design-system/guides/updating-to-v10.njk
We made a small mistake in the v10 upgrade guide by saying that the javascripts path in the templates used to be `nhsuk-frontend.min.js` but it actually used to be `nhsuk.min.js`.
We've also realised that the path prefix is not necessarily `/javascripts/` but can vary depending on your setup (eg the NHS prototype kit uses `/nhsuk-frontend/`). So this makes that clearer by using `<JAVASCRIPTS-PATH>` to hopefully make it clear that that bit isn't part of the upgrade guidance.
> Fix to previous javascripts path
