nhsuk/nhsuk-service-manual

app/views/content/formatting-and-punctuation.njk, app/views/content/how-we-write.njk, app/views/content/inclusive-language.njk, app/views/content/voice-and-tone.njk, app/views/content/writing-for-accessibility.njk, app/views/contribute.njk, app/views/cookies.njk, app/views/includes/footer.njk, app/views/index.njk, app/views/practices/make-your-service-accessible.njk, app/views/privacy-policy.njk, app/views/sitemap.njk, app/views/terms-and-conditions.njk, package-lock.json, package.json
- Content style guide 2nd level pages, except A to Z (will do tomorrow)
- Practices 2nd level page
- Contribute
- Cookies
- Sitemap
- Privacy policy
- Terms and conditions
=> Populated a bunch of pages

app.js, middleware/authentication.js, package-lock.json, package.json
- Add a username and password to the website when its deployed to production, to avoid people stumbling across the service manual whilst its in development.
- Change gulp dependencies to be production dependencies
- Create a 'build' task to compile scss to css.
=> Password protect service manual in prod

azure-pipelines.yml
Run a build when the develop branch is pushed to.
=> Build from develop

app/styles/_app.scss, app/views/design-principles.njk
Fixed the Design Principles styling issues for mobile.
=> Fixed design principles styling issues for mobile

app/styles/design-example/_code-snippet.scss, app/styles/design-example/_design-example.scss, app/views/includes/design-example-wrapper.njk
- Make background grey
- Tweak margin and padding
=> Design example styles

app/views/includes/design-example.njk, app/views/styles-components-patterns/grid.njk
Turn off the iframe code example when showExample is set to false
=> Add a `showExample` option

app/components/grid-overrides-any-breakpoint.njk, app/components/grid-overrides-tablet-desktop.njk, app/components/grid-page-width.njk, app/components/grid-rows.njk, app/components/grid-spacing.njk, app/components/grid-wrappers.njk, app/views/privacy-policy.njk, app/views/styles-components-patterns/grid.njk, app/views/styles-components-patterns/inset-text.njk, app/views/styles-components-patterns/typography.njk, app/views/styles-components-patterns/warning-callout.njk
- Added the design example functionality to the grid page
- Added the design example functionality to the typography page
- Made a few content updates and tweaks
=> Add design example to styles + content updates

app/components/button-reverse.njk, app/components/button-secondary.njk, app/components/button.njk, app/components/checkboxes.njk, app/components/date-input-errors.njk, app/components/date-input.njk, app/components/fieldset.njk, app/components/hint-text.njk, app/views/practices/make-your-service-accessible.njk, app/views/styles-components-patterns/buttons.njk, app/views/styles-components-patterns/checkboxes.njk, app/views/styles-components-patterns/date-input.njk, app/views/styles-components-patterns/error-message.njk, app/views/styles-components-patterns/error-summary.njk, app/views/styles-components-patterns/fieldset.njk, app/views/styles-components-patterns/hint-text.njk
Added design example to: fieldset, error-summary, error-message, checkboxes, hint-text, buttons, date-input.
=> Add design examples

app/views/styles-components-patterns.njk, app/views/styles-components-patterns/buttons.njk, app/views/styles-components-patterns/checkboxes.njk, app/views/styles-components-patterns/date-input.njk, app/views/styles-components-patterns/error-message.njk, app/views/styles-components-patterns/error-summary.njk, app/views/styles-components-patterns/fieldset.njk, app/views/styles-components-patterns/hint-text.njk, app/views/styles-components-patterns/radios.njk, app/views/styles-components-patterns/select.njk, app/views/styles-components-patterns/text-input.njk, app/views/styles-components-patterns/textarea.njk
Add new components and update existing components with links to each other
=> Update components files - new and linked

app/views/content-style-guide.njk, app/views/content/how-we-write.njk, app/views/content/writing-for-accessibility.njk, app/views/index.njk, app/views/practices.njk
Updated content style guide pages to link to health literacy page and updated words on practices pages.
=> Update content in style guide and practices pages

app/views/styles-components-patterns/grid.njk
Update Grid page date to reflect latest code changes.
=> Update grid page date after changes

app/views/sitemap.njk, app/views/styles-components-patterns/error-message.njk
- Update sitemap with latest pages
- Fix example width in 'error-message'
=> Update sitemap and fix width

middleware/authentication.js
Remove the production password protection for the https://beta.nhs.uk/service-manual deployment this afternoon.
=> Remove production password ready for beta deployment

app/views/sitemap.njk, app/views/styles-components-patterns.njk, app/views/styles-components-patterns/select.njk
- Add 'hint-text' and 'select' to 'sitemap'
- Add 'select' to 'styles-components-patterns'
- Fix width for the design example in 'select'
=> Update sitemap and styles-components-patterns

app/views/content/a-to-z-of-NHS-health-writing.njk, app/views/styles-components-patterns/details.njk, app/views/styles-components-patterns/expander.njk, app/views/styles-components-patterns/images.njk, app/views/styles-components-patterns/table.njk
Amend typo in A to Z - remove one full stop. Also update content on 4 new component pages.
=> Amend typo in A to Z and update 4 new components

app/components/skip-link.njk, app/views/styles-components-patterns/back-link.njk, app/views/styles-components-patterns/pagination.njk, app/views/styles-components-patterns/skip-link.njk
I've updated content and examples on skip link, back page and pagination components.
=> Contentupdate

app/components/details.njk, app/components/error-summary.njk, app/components/expander-group.njk, app/components/hint-text.njk, app/components/input-hint-text.njk, app/components/radios-divider.njk, app/components/review-date.njk, app/components/skip-link.njk, app/views/content/a-to-z-of-NHS-health-writing.njk, app/views/styles-components-patterns/back-link.njk, app/views/styles-components-patterns/buttons.njk, app/views/styles-components-patterns/contents-list.njk, app/views/styles-components-patterns/date-input.njk, app/views/styles-components-patterns/error-message.njk, app/views/styles-components-patterns/error-summary.njk, app/views/styles-components-patterns/expander.njk, app/views/styles-components-patterns/hint-text.njk, app/views/styles-components-patterns/images.njk, app/views/styles-components-patterns/index.njk, app/views/styles-components-patterns/pagination.njk, app/views/styles-components-patterns/radios.njk, app/views/styles-components-patterns/review-date.njk, app/views/styles-components-patterns/skip-link.njk, app/views/styles-components-patterns/text-input.njk
Change design examples and other content
Change as follows:
app/components/details.njk - Amend design example 
app/components/error-summary.njk - Change code example wording 
app/components/expander-group.njk - Correct typo - and in expander group code example 
app/components/hint-text.njk - Change hint text wording only and date to February 2019 
app/components/input-hint-text.njk - Change hint text to reflect hint text page.  Note line spacing in input-hint-text.njk isn’t right yet.   
app/components/radios-divider.njk - Change NHS.UK login to NHS login 
app/components/review-date.njk - Update date in design example. 
app/components/skip-link.njk - Amend wording of design example. 
app/views/content/a-to-z-of-NHS-health-writing.njk - Typo change …
=> Change design examples and other content

deploy/terraform/web-app.tf
=> Adjust web-app deploy to be HTTPS only.

CHANGELOG.md, app/views/content/a-to-z-of-NHS-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/styles-components-patterns/index.njk
Update A to Z page after Style Council meeting. 
Update date on UI styles, components and patterns page after adding new components pages.
Update formatting page to reflect changes to temperature, with link to new section, in A to Z page.
3 commits.
=> Add to A to Z page

CHANGELOG.md, app/views/content/a-to-z-of-NHS-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/frontend-library/index.njk, app/views/prototyping-tools/index.njk, app/views/styles-components-patterns/index.njk, azure-pipelines.terraform.yml, azure-pipelines.yml, deploy/terraform/web-app.tf, package-lock.json, package.json
- Deployment and infrastructure improvements by @midgleyc 
- Add more terms to A to Z of NHS health writing after January Style Council meeting
- Update temperature info on Formatting and punctuation page and link to A to Z
- Fix references to nhs.uk / the NHS website / NHS.UK (programme)
=> Release 1.1.1

app/views/practices/index.njk
more link fixes that were pointing to the azure site
=> more dynamic link fixes

app/scripts/cookieConsent.js
Link wasn't updated when the site was moved to beta nhs but it isn't static now
=> updated cookie banner link to not be static

app/views/design-principles/index.njk, app/views/index.njk, package-lock.json
Fixing heading levels on the home page and the design principle page.
Also tidied up the package-lock.json file.
=> Fix heading levels

app/views/service-standard/1-understand-users-and-their-needs-context-health-and-care.njk, app/views/service-standard/2-work-towards-solving-a-whole-problem.njk, app/views/service-standard/index.njk
Update index page with new point about care and other changes.
Update page for point 1.
Rename page for point 2 and update it.
=> Update service standard

app/views/contribute.njk, app/views/contribute/criteria.njk, app/views/contribute/propose-new-thing.njk, app/views/contribute/work-new-thing.njk
Updated date for contribute section pages
=> Contribute

app/views/content/a-to-z-of-NHS-health-writing.njk
Added agreed new terms, including Fahrenheit, fart, wind, bottom, anus etc.
=> Update A to Z after Style Council meeting

app/views/styles-components-patterns/draft/a-to-z.njk, app/views/styles-components-patterns/draft/feedback-banner.njk, app/views/styles-components-patterns/draft/mini-hub.njk
Change minihubs page, feedback banner and A to Z.
Note A to Z rather than A-Z.
=> Update 3 components files

CHANGELOG.md, app.js, app/config.js, app/locals.js, app/views/includes/design-example-wrapper.njk, app/views/includes/layout.njk, app/views/includes/template.njk, gulpfile.js, package-lock.json, package.json
- Prevent the CSS and JavaScript files being cached for too long with cache busting
resolves #185
=> Release 1.4.1

CHANGELOG.md, app/views/content/a-to-z-of-NHS-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/content/how-we-write.njk, app/views/content/inclusive-language.njk, app/views/content/index.njk, app/views/content/links-and-pdfs.njk, app/views/content/numbers-dates-time-measurement.njk, app/views/content/voice-and-tone.njk, app/views/content/writing-for-accessibility.njk, package-lock.json, package.json
Add small content changes to 2 content style guide files.
=> Update style guide after Style Council

app/views/styles-components-patterns/a-to-z.njk
=> Patterns write up

app/views/styles-components-patterns/a-to-z.njk, app/views/styles-components-patterns/mini-hub.njk
@bencullimore Your earlier changes were fine. Adam has merged them. These are a few final tweaks. Would you mind casting an eye over them please and then merging? I'll have a final look at everything when merged but I think it's all done now.
=> Update A to Z and minihub with minor changes

app/views/accessibility-statement.njk
Do not merge yet. Hold pending other commits.
=> Add accessibility statement to service manual

app/views/includes/footer.njk, app/views/privacy.njk, app/views/styles-components-patterns/colour.njk, app/views/styles-components-patterns/index.njk
Update but hold and publish with accessibility guidance
=> Bring components pages into line with accessibility guidance

app.js, app/views/accessibility/partials/write-content-thats-easy-to-understand.njk, app/views/content/health-literacy/index.njk, app/views/content/health-literacy/use-a-readability-tool-to-prioritise-content.njk, app/views/content/how-we-write.njk, app/views/content/index.njk, app/views/content/links-and-pdfs.njk, app/views/content/partials/related-nav.njk, app/views/service-standard/4-make-sure-everyone-can-use-the-service.njk, app/views/sitemap.njk
Change content index page and tweak 2 other page.
=> Tweak content section

app.js
Need to run some automated checks on the staging environment - which the checker is struggling to do with a password on the environment.
=> temporarily remove password from staging

app/styles/main.scss
- fix details + heading-l (h2) spacing
- fix expander background colour in white section
=> Fix details + header padding

app/views/accessibility/content.njk, app/views/accessibility/design.njk, app/views/accessibility/development.njk, app/views/accessibility/getting-started.njk, app/views/accessibility/partials/make-users-aware-of-status-updates-away-from-current-focus.njk, app/views/accessibility/partials/recruit-people-with-access-needs.njk, app/views/accessibility/partials/set-language.njk, app/views/accessibility/partials/test-that-text-sizes-and-zooms-correctly.njk, app/views/accessibility/partials/try-out-assistive-technologies.njk, app/views/accessibility/partials/understand-participants-needs-before-you-test.njk, app/views/accessibility/partials/use-alternative-text-for-functional-images.njk, app/views/accessibility/partials/use-alternative-text-for-images-in-content.njk, app/views/accessibility/product-and-delivery.njk, app/views/accessibility/testing.njk, app/views/accessibility/user-research.njk
Move chunk on trying out assistive tech and remove links from activities pages.
=> Accesscontent

app/views/accessibility/getting-started.njk, app/views/accessibility/how-to-make-digital-services-accessible.njk, app/views/accessibility/partials/ask-questions-at-the-start-of-the-project.njk, app/views/accessibility/partials/check-colour-contrast.njk, app/views/accessibility/partials/check-keyboard-accessibility.njk, app/views/accessibility/partials/check-that-accessibility-is-done.njk, app/views/accessibility/partials/define-skip-links.njk, app/views/accessibility/partials/do-not-include-text-in-images.njk, app/views/accessibility/partials/label-form-fields-clearly.njk, app/views/accessibility/partials/make-sure-everyone-knows-their-responsibilities.njk, app/views/accessibility/partials/make-your-research-more-accessible-on-the-day.njk, app/views/accessibility/partials/monitor-and-record-your-work.njk, app/views/accessibility/partials/set-page-titles.njk, app/views/accessibility/partials/test-that-text-sizes-and-zooms-correctly.njk, app/views/accessibility/partials/understand-participants-needs-before-you-test.njk, app/views/accessibility/partials/use-alternative-text-for-images-in-content.njk, app/views/accessibility/partials/use-aria-patterns.njk, app/views/accessibility/partials/write-good-link-and-form-control-names.njk, app/views/sitemap.njk
Make minor amendments to site map and to accessibility guidance.
=> Update accessibility guidance and sitemap

CHANGELOG.md, app/views/contribute.njk, app/views/includes/layout.njk, app/views/sitemap.njk
- Remove page section from the Open Graph meta title
- Fix broken link to the privacy policy on the sitemap page
- Update the link to the contribution criteria
=> General updates and bug fixes 

CHANGELOG.md, app/views/accessibility/partials/look-after-your-team.njk, app/views/contribute.njk, app/views/includes/layout.njk, app/views/sitemap.njk, package-lock.json, package.json
- Remove page section from the Open Graph meta title
- Fix broken link to the privacy policy on the sitemap page
- Update the link to the contribution criteria
=> Release 1.6.1

app.js, middleware/page-index.js, package-lock.json
=> Fix service manual search

app.js, app/scripts/main.js, app/scripts/search.js, middleware/page-index.js, package-lock.json, package.json, tests/page-index.spec.js
- fixed search input showing [object object] on selection
- fixed search not working in mobile mode
- added unit tests for page indexer
- indexer no longer index promo links
=> service manual search fixes

app/views/content/how-we-write.njk
Added sentence about short words - "get" rather than "experience" etc
=> Update to "How we write" section

app/views/content/links-and-pdfs.njk
Changed date to August 2019 from July 2019
=> Amended updated date

app/views/index.njk
issue #122
Updated get in touch info
=> Updated slack address and workspace name

app/views/styles-components-patterns/a-to-z.njk
Changed from:
Join us on the NHS.UK service manual Slack workspace or email us at service-manual@nhs.net
To:
Join us on the service manual Slack workspace [keep link] or email us at service-manual@nhs.net
=> Updated contact details

app/views/content/a-to-z-of-nhs-health-writing.njk
Instead of: "If people might come across the microgram symbol, for example on their medicines packet, …",changed to;
"We only use the symbol if people will find it helpful, for example, if they are likely to see it on their medicines or vitamins packet."
=> Amend microgram info

app.js, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/includes/header.njk, app/views/includes/layout.njk, middleware/README.md, middleware/page-index-additions.js, middleware/page-index.js, tests/page-index.spec.js
- Fixed search crash when page wasn't indexed correctly
- Fixed search crash when no query is supplied
- Added readme for search
- Moved search url to same format as other service-manual urls
- Made page indexer error logs easier to read
=> Search docs and small fixes

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/index.njk, app/views/styles-components-patterns/a-to-z.njk
Small changes made to 3 pages.
=> Add minor changes after GitHub training

app/views/content/a-to-z-of-nhs-health-writing.njk
Proofed and amended ids in file.
=> Amend ids in A to Z

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/content/index.njk, app/views/content/numbers-measurement-dates-time.njk, app/views/content/partials/related-nav.njk, package-lock.json
populate the numbers, dates, time and measurement pages. Update the links on the other pages to this new page and remove old content.
=> create the numbers, dates, time and measurement pages

CHANGELOG.md, package-lock.json, package.json
update package dependencies to latest versions and populate the change log for recent changes.
=> update package dependencies to latest versions

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/numbers-measurement-dates-time.njk
Added in some bits that dropped out in last merge and proofed file. Also added 2 new links from A to Z.
=> Add missing sections to numbers file with links from A to Z

app/views/sitemap.njk, app/views/sitemap.xml
Dropped link to new numbers file into sitemap.
I haven't updated sitemap.xml. @AdamChrimes, would you mind doing that please?
=> Add new numbers file to sitemap

app/styles/main.scss, app/views/content/formatting-and-punctuation.njk, app/views/content/numbers-measurement-dates-time.njk
Updated the `page contents` styling on the `Formatting and punctuation` and `Numbers measurement dates time` pages.
=> Page contents

CHANGELOG.md, app.js, app/views/includes/header.njk, app/views/includes/search.njk, app/views/sitemap.xml, package-lock.json, package.json
Reverts nhsuk/nhsuk-service-manual#264
Remove duplicate entry from the XML sitemap
Temporarily remove the password from the staging environment for user testing
=> Add the search functionality back and remove duplicate sitemap entry

app/views/accessibility/partials/look-after-your-team.njk
Bring apostrophe into line with our recommended style.
=> Correct apostrophe in look-after-your-team.njk

app/views/content/a-to-z-of-nhs-health-writing.njk
2 new terms in the content style A to Z after 18 July Style Council meeting.
=> Update A to Z with entries for health record and medical record

app/views/includes/layout.njk
Note: This is only for the staging environment whilst we test some functionality
=> Added Hotjar tracking code

app/views/styles-components-patterns/care-cards.njk
Update card card page with new content for content designers, as agreed at 18 July Style Council meeting 
@AdamChrimes or @davidhunter08, if you could merge this with develop please, I will ask a few content designers to check it on staging before we publish. Thanks a lot.
=> Carecardchanges

app/views/content/a-to-z-of-nhs-health-writing.njk
=> Add 'summary care record' to A Z page

app/views/content/how-we-write.njk
We need straight apostrophes please.
=> Change curly apostrophes to straight ones

app/views/content/a-to-z-of-nhs-health-writing.njk
Add new entry to P on personal health records.
=> Update A-Z style guide

app/views/accessibility/how-to-make-digital-services-accessible.njk
Please. Old apostrophes were curly, we need straight ones.
=> Amend apostrophes so they're straight

app/views/content/index.njk
=> Update slack address

app.js
Password authentication added back to the staging environment following user testing for the search functionality
=> add password auth back to the staging environment

app/views/content/numbers-measurement-dates-time.njk
Just changed a couple of instances of 'don't' to 'do not', plus changed the sentence about how we use ordinals.
=> Update measurements and numbers page

app/views/content/inclusive-language.njk
=> Update as per card #140

deploy/terraform/backend.tf, deploy/terraform/versions.tf, deploy/terraform/web-app.tf
Also update terraform to 0.12 as that's what's now running on the Azure agents and felt I may as well.
=> Update terraform to allow creation of review branches from pull requests

app/views/content/write-good-questions/1-start-with-discovery.njk, app/views/content/write-good-questions/2-make-sure-you-need-each-question.njk, app/views/content/write-good-questions/3-get-the-questions-into-order.njk, app/views/content/write-good-questions/4-treat-it-like-a-conversation.njk, app/views/content/write-good-questions/5-be-careful-with-yes-no-questions.njk, app/views/content/write-good-questions/6-write-the-content-around-the-questions.njk, app/views/content/write-good-questions/7-test-your-questions.njk
Add more content to writegoodquestions.
=> Iterate questions

app/views/content/inclusive-language.njk
Make 2 small changes - add "heritage" to "ethnic" and say "the" GP, rather than "your".
=> Tweak language on inclusive language page

app/views/content/a-to-z-of-nhs-health-writing.njk
Add the term 'Sleepy' to the A to Z of NHS health writing as per https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/147
=> Update to A to Z of NHS health writing - Sleepy

app/views/content/a-to-z-of-nhs-health-writing.njk
Add "sedating" to A to Z.
https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/148
=> Update A to Z to add "sedating" 148

app/views/content/health-literacy/use-a-readability-tool-to-prioritise-content.njk
Quotation changed in Readability tool page 128
=> Update the quote marks

app/views/content/index.njk
=> updated content on content style guide overview page

app/styles/main.scss, app/views/accessibility/index.njk, app/views/community/index.njk, app/views/components/index.njk, app/views/content/index.njk, app/views/get-started/index.njk, app/views/patterns/index.njk, app/views/styles/index.njk
- Hide the search bar within the header until the development on search is completed
- Add a navigation to index pages on mobile pages (mobile & tablet)
=> Section index page mobile navigation

app/views/content/a-to-z-of-nhs-health-writing.njk
Tweak wording on seizure or fit following last minute feedback.
=> Update entry on seizure or fit

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/health-literacy/index.njk, app/views/content/health-literacy/use-a-readability-tool-to-prioritise-content.njk, app/views/content/inclusive-language.njk, package-lock.json, package.json
:new: **New content**
- Add new entries to A to Z of NHS health writing, including: "baby", "foetus", "drowsy", "sleepy", "preconception care", "seizure or fit"
- Add mini-hub at top of Inclusive language page and change "baby" in section on Age
- Update entry for summary care record in A to Z of NHS health writing
=> Release 1.10.0

app/views/content/how-we-write.njk
Add contraction to accurate paragraph.
=> Add contraction

CHANGELOG.md, app/views/content/how-we-write.njk, package-lock.json, package.json
- Use the latest version of the NHS.UK frontend library (v2.3.1)
=> Release 1.10.1

CHANGELOG.md, app.js, app/scripts/main.js, app/views/content/how-we-write.njk, package-lock.json, package.json
- Remove the search JavaScript until the search functionality is complete
=> Release 1.10.2

app/components/typography-headings.njk, app/views/includes/footer.njk, app/views/styles-components-patterns/typography.njk
- Updated incorrect class names for headings on the typography page.
- Removed link to the survey in the footer.
=> Headings and survey

app/views/content/a-to-z-of-nhs-health-writing.njk
=> Change link about NHS App

app/views/content/a-to-z-of-nhs-health-writing.njk
Update after last style council meeting
=> Add PMS (premenstrual syndrome) and premenstrual syndrome

app/views/content/a-to-z-of-nhs-health-writing.njk
Change following previous edit typo
=> Change error in PMS (premenstrual syndrome) header

app/views/content/a-to-z-of-nhs-health-writing.njk
Change following content style council
=> Change wording of seizure or fit

app/views/content/how-to-write-good-questions/1-understand-the-problem-before-you-write-your-questions.njk, app/views/content/how-to-write-good-questions/index.njk, app/views/content/how-to-write-good-questions/introduction-what-is-a-form.njk, app/views/content/how-to-write-good-questions/write-good-questions-nav.njk
- removed the 3 what is a form? examples
- added 'What is a form?' content to the index page
- renamed the index page to 'Introduction'
- updated nav (page nav and pagination urls)
=> Merged 'Index' and 'Introduction - what is a form?' page

app/views/content/a-to-z-of-nhs-health-writing.njk
=> Change wording about GP practice

app/views/content/how-to-write-good-questions/index.njk
Simplified "What is a form?" section. Rewrote it and "Forms design and this quidance" section to avoid mention of 3 layers. 
Amended "Community" section to remove reference to 3 layers.
Added new "Help us improve this guidance" section.
=> Amend intro page after design review

app/views/accessibility/partials/involve-people-with-access-needs-at-every-stage.njk
Remove wizard behind the curtain example following user research feedback
=> Remove wizard behind the curtain example

app/views/content/how-to-write-good-questions/1-understand-the-problem-before-you-write-your-questions.njk
Reworked main headings.
Deleted mention of 3 layers. 
Added Read more section.
=> Update Understand the problem page

app/views/content/how-to-write-good-questions/1-understand-the-problem-before-you-write-your-questions.njk, app/views/content/how-to-write-good-questions/2-make-sure-you-need-each-question.njk, app/views/content/how-to-write-good-questions/3-consider-the-sensitivities-around-your-questions.njk, app/views/content/how-to-write-good-questions/4-use-yes-no-questions-but-be-careful.njk, app/views/content/how-to-write-good-questions/5-get-the-questions-into-order.njk, app/views/content/how-to-write-good-questions/6-think-of-the-form-as-a-conversation.njk, app/views/content/how-to-write-good-questions/7-write-the-supporting-content-for-your-form.njk, app/views/content/how-to-write-good-questions/8-test-your-questions.njk, app/views/content/how-to-write-good-questions/write-good-questions-nav.njk
Change order of pages
Rename some pages
Update nav and links, including to new sensitivities page
=> Amend nav and links

app/views/content/how-to-write-good-questions-for-forms/4-use-yes-no-questions-but-be-careful.njk, app/views/content/how-to-write-good-questions-for-forms/5-get-the-questions-into-order.njk
Tweak Yes No questions page. 
Review order of information about getting questions into order. Remove bullet points.
=> Iterate Yes No questions and ordering questions

app/views/content/how-to-write-good-questions-for-forms/consider-the-sensitivities-around-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/get-the-questions-into-order.njk, app/views/content/how-to-write-good-questions-for-forms/index.njk, app/views/content/how-to-write-good-questions-for-forms/make-sure-you-need-each-question.njk, app/views/content/how-to-write-good-questions-for-forms/test-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/think-of-the-form-as-a-conversation.njk, app/views/content/how-to-write-good-questions-for-forms/understand-the-problem-before-you-write-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/use-yes-no-questions-but-be-careful.njk, app/views/content/how-to-write-good-questions-for-forms/write-good-questions-nav.njk, app/views/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form.njk, app/views/styles-components-patterns/start-page.njk
Take numbers out of file names and amend links etc.
=> Change file names and nav and links

app/views/accessibility/partials/define-focus-styles.njk, app/views/styles-components-patterns/colour.njk, app/views/styles-components-patterns/understanding-focus-state-styles.njk
Amended focus state styles page - location and content
Amended colours page plus accessibility page re focus styles.
=> Make focus state changes to 3 files

app/components/checkboxes-error-messages.njk, app/components/checkboxes-hint.njk, app/components/input-hint-text.njk, app/components/radios-hints-options.njk, app/components/textarea-error.njk, app/components/textarea-longer.njk, app/components/textarea.njk, app/views/styles-components-patterns/checkboxes.njk, app/views/styles-components-patterns/date-input.njk, app/views/styles-components-patterns/details.njk, app/views/styles-components-patterns/fieldset.njk, app/views/styles-components-patterns/radios.njk, app/views/styles-components-patterns/text-input.njk, app/views/styles-components-patterns/textarea.njk
Went through updated component pages.
=> Reviewed component changes

app/components/summary-list-without-action.njk, app/components/summary-list-without-border.njk, app/components/summary-list.njk, app/views/styles-components-patterns/summary-list.njk
Work in progress.
Guidance for the summary list component.
=> Summary list

app/views/content/a-to-z-of-nhs-health-writing.njk
All good to be put into develop: Sara to review once done.
=> add nhs number to a to z and remove 'the'

app/views/content/a-to-z-of-nhs-health-writing.njk
Add link on NHS number A to Z to NHS number pattern page.
=> Add link on NHS number A to Z

app/views/content/voice-and-tone.njk
Add link to form as a conversation page on write good questions
=> Add link to write good questions

app/views/styles-components-patterns/summary-list.njk
=> Tweak wording about experimental status for summary list

app/views/styles-components-patterns/summary-list.njk
Minor change - should be final now.
=> Tweak wording re experimental

CHANGELOG.md, app/views/sitemap.njk, app/views/sitemap.xml, package-lock.json, package.json
- update the sitemap with new guidance pages
- populate the changelog for 1.13.0 and bump version
=> Sitemap and change log updates

app/views/content/how-to-write-good-questions-for-forms/make-sure-you-need-each-question.njk, app/views/content/how-to-write-good-questions-for-forms/test-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users.njk
Final changes after talking with Nancy.
=> Iterate test questions

app/views/styles-components-patterns/summary-list.njk
Use the correct `--no-border` css modifier, not `--without-border`
=> Fix summary list css class documentation

CHANGELOG.md, app/components/a-z-list-panel.njk, app/components/a-z-nav.njk, app/views/styles-components-patterns/a-to-z.njk, app/views/styles-components-patterns/mini-hub.njk
fix the Nunjucks snippets for the A to Z and Mini-hub patterns and also tidy up the pages for HTML formatting and spacing
=> fix the Nunjucks snippets for the A to Z and Mini-hub patterns

app/views/content/pdfs.njk
Remove mention of PDF/As being more accessible in PDF page
=> Remove mention of PDF/As being more accessible

app/views/content/pdfs.njk
Added an additional bullet point on PDFs being used as a permanent record.
=> Add point to PDFs

app/views/content/partials/related-nav.njk
Add in link to How to write good questions for forms.
=> Update nav in content style guide

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk
Add full sentence bullet list to formatting page and add food pipe and medicine to A to Z of health writing.
=> Update lists and A to Z

app/views/includes/layout.njk, app/views/service-standard/1-understand-users-and-their-needs-context-health-and-care.njk, app/views/service-standard/10-define-what-success-looks-like-and-be-open-about-how-your-service-is-performing.njk, app/views/service-standard/11-choose-the-right-tools-and-technology.njk, app/views/service-standard/12-make-new-source-code-open.njk, app/views/service-standard/13-use-and-contribute-to-open-standards-common-components-and-patterns.njk, app/views/service-standard/14-operate-a-reliable-service.njk, app/views/service-standard/15-support-a-culture-of-care.njk, app/views/service-standard/16-make-your-service-clinically-safe.njk, app/views/service-standard/17-make-your-service-interoperable.njk, app/views/service-standard/2-and-3-work-towards-solving-a-whole-problem-and-provide-a-joined-up-experience.njk, app/views/service-standard/4-make-the-service-simple-to-use.njk, app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk, app/views/service-standard/6-create-a-team-that-includes-multidisciplinary-skills-and-perspectives.njk, app/views/service-standard/7-use-agile-ways-of-working.njk, app/views/service-standard/8-iterate-and-improve-frequently.njk, app/views/service-standard/9-respect-and-protect-users-confidentiality-and-privacy.njk, app/views/service-standard/about.njk, app/views/service-standard/index.njk, app/views/sitemap.njk
- Remove the nofollow metadata from the service standard pages
- Add the service standard pages to the sitemap so they are captured by the search functionality
=> Update the service standard pages

app/views/content/inclusive-language.njk
Make further changes based on recent feedback and review.
=> Update inclusive language page

app/views/service-standard/2-and-3-work-towards-solving-a-whole-problem-and-provide-a-joined-up-experience.njk, app/views/service-standard/about.njk
Update service standard points 2 and 3.
=> Update points 2 and 3

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/inclusive-language.njk
Changed wording around assigned versus registered at birth plus A to Z entry on same.
=> Tweak inclusive language page and add A to Z entry

app/views/styles-components-patterns/details.njk
Remove link and clarify direction to research in details page.
=> Remove link in details page

app/views/styles-components-patterns/details.njk
Change internal link to research section.
=> Update research link

app/views/content/formatting-and-punctuation.njk
Correct unordered bullets in full sentence key fact bullet list section.
=> Correct full sentence bullets

app/views/service-standard/17-make-your-service-interoperable.njk
As discussed with @sarawilcox - please review. Can wait until after xmas ;-)
=> Added some more standards

CHANGELOG.md, app/views/content/inclusive-language.njk
Bring recent inclusive language changes into staging environment.
=> Inclusive language

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/numbers-measurements-dates-time.njk
Add A to Z entries for pharmacy, chemist and sex assigned or registered at birth, and update numbers page
=> Update A to Z and numbers pages

app/views/community/index.njk, app/views/includes/_contact-panel.njk, app/views/index.njk
Checked promo boxes.
Updated What's new.
Tweaked content-panel and brought Get in touch at bottom of page into line with it.
Amended community home page.
=> Update home page, contact-panel and community index page

CHANGELOG.md, package-lock.json, package.json
update dependencies to the latest versions & use the correct version number for the release.
=> update dependencies to the latest versions

app/views/content/formatting-and-punctuation.njk
Correct link url for numbers, measurements, date and time link
=> Correct link url

app/views/whats-new/blog-posts.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
=> Update content in What's new

app/views/whats-new/blog-posts.njk, app/views/whats-new/index.njk
Add medium blogs and blog sources.
=> add blogs and blog sources

app/views/community/backlog-of-components-and-patterns.njk, app/views/community/index.njk, app/views/includes/_side-nav.njk, app/views/sitemap.njk
Rename and update page to clarify which backlog.
=> Update backlog page

CHANGELOG.md, app/styles/main.scss, app/views/includes/_header-prototype.njk, app/views/includes/_header.njk, app/views/includes/search.njk, app/views/page-not-found.njk, package-lock.json, package.json
- update the 404 page content and add a var to disable search
- install latest dependencies and add repository field
=> update the 404 page content and add a var to disable search

.babelrc, CHANGELOG.md, app/scripts/search.js, app/styles/app/_search.scss, app/views/content/formatting-and-punctuation.njk, app/views/content/how-to-write-good-questions-for-forms/_layout.njk, app/views/content/how-to-write-good-questions-for-forms/index.njk, app/views/content/how-to-write-good-questions-for-forms/write-good-questions-nav.njk, app/views/includes/search.njk, app/views/sitemap.njk, middleware/authentication.js, middleware/page-index.js, middleware/routing.js, package-lock.json, package.json, tests/page-index.spec.js
- Display the parent page in search results
=> Release: Search improvements

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/whats-new/updates.njk
Updated updates page and added four entries to A to Z.
=> updated updates page and A to Z

app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Reformatted the updates page, and the latest updates section in the what's new page.
=> updated updates and what's new pages

app/views/whats-new/index.njk, app/views/whats-new/show-and-tells.njk
Typos in show and tells section.
=> Tweak content

app/styles/main.scss, app/views/accessibility/partials/use-tables-to-show-relationships-between-data.njk, app/views/community/contribution-criteria.njk, app/views/whats-new/updates.njk
- remove `nhsuk-u-margin-bottom0`  from table elements
- add sass to `.nhsuk-table__cell` to remove the margin-bottom
=> Table element (<p>) margin bottom

app/views/content/formatting-and-punctuation.njk
Remove repetition in formatting and punctuation page
=> Remove repetition

app/views/community/contribution-criteria.njk
Remove negative contractions from contribution criteria page.
=> Remove negative contractions

app/views/accessibility/index.njk
Remove negative contraction on accessibility index
=> Remove negative contraction

CHANGELOG.md, app/views/includes/layout.njk, package-lock.json, package.json
- add temporary meta data to verify domain with Google
- update package dependencies to latest versions
=> add temporary meta data to verify domain with Google

CHANGELOG.md, app/config.js, app/locals.js, app/views/includes/design-example-wrapper-full.njk, app/views/includes/design-example-wrapper.njk, app/views/includes/layout.njk, app/views/includes/template.njk, package-lock.json, package.json, webpack.config.js
Remove old CSS/JS caching techniques as this is now covered on the server side. We have better caching setup our server side firewall and there has been known issues with the HTML caching giving the CSS/JS a 404.
=> Fix cache techniques

app/views/content/numbers-measurements-dates-time.njk
Add a few sentences under headings.
Correct portions content.
Change headings on where we do not use numerals.
=> Tweak examples and what we say about temperature

CHANGELOG.md, app/styles/design-example/_code-snippet.scss, app/styles/design-example/_design-example.scss, app/views/includes/design-example.njk
**Old**
```
<a href="/design-example/error-summary" class="design-example__pop-out" target="_blank">
Open <span class="nhsuk-u-visually-hidden">error summary</span> example in new window
</a>
```
**New**
```
<a href="/design-example/error-summary" class="design-example__pop-out" target="_blank">
Open this <span class="nhsuk-u-visually-hidden">error summary</span> example in new window
</a>
```
=> Design example 'Open in a new window' link

app/components/hint-text.njk
=> fix NHS number typo

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/inclusive-language.njk, app/views/content/index.njk, app/views/content/numbers-measurements-dates-time.njk
Update after Jan Style Council meeting:
- add new entry in A to Z of NHS health writing for "GP" and update entry for "doctor"
- add explanation about using months up to 2 years on Inclusive language page
- improve guidance on ordinal numbers on Numbers, measurements, dates and time page
- add new guidance on telephone numbers to A to Z of NHS health writing, based on GOV.UK guidance
- remove reference to the Oxford Dictionary for Writers and Editors on content style guide hub page and include contact details instead
=> Jan style council

CHANGELOG.md, package-lock.json, package.json
Exactly what it says on the tin
=> use the latest version of nhsuk-frontend (3.0.3)

CHANGELOG.md, app/components/checkboxes-error-messages.njk, app/components/checkboxes-hint.njk, app/components/error-message-in-context.njk, app/components/error-summary-link-input.njk, app/components/error-summary-link-multiple-input.njk, app/components/error-summary-link-options.njk, app/components/error-summary-placement.njk, app/components/nhs-number-error.njk, app/components/nhs-number-filter-single.njk, app/components/nhs-number-filter-third-option.njk, app/components/nhs-number-filter.njk, app/components/nhs-number-single.njk, app/styles/design-example-overrides.scss, app/styles/design-example/_design-example.scss, app/views/design-system/components/error-message.njk, app/views/design-system/components/error-summary.njk, app/views/includes/design-example-wrapper-full-layout.njk, app/views/includes/design-example-wrapper-full.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Add new guidance and examples of an error summary and an error message working together.
See [community backlog issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/189)
=> Update error summary guidance

CHANGELOG.md, app/components/nhs-number-error.njk
Add error summary to NHS number pattern with errors example.
=> Update nhs number pattern with error example

CHANGELOG.md, app/views/content/index.njk
=> Add BBC radio interview to content style guide

.github/PULL_REQUEST_TEMPLATE.md
Add a simple pull request template with a checklist to consider for changes
=> create a pull request template

app.js, app/config.js, package-lock.json, package.json
https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs
=> install Azure Application Insights

app.js
only use Azure Application Insights if setup with a key
=> only use Azure Application Insights if setup

app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Added Patterns page updates to other recent What's new and Updates page updates
Patterns changes in PR#584 and branch "patterns"
I've put What's new updates here so we can view them together with other What's new updates.
=> Add patterns page updates to What's new

CHANGELOG.md, app/styles/main.scss, app/views/includes/_feedback-banner.njk, app/views/includes/app-layout.njk, app/views/includes/layout.njk, app/views/index.njk
Add feedback banner so that users can fill in a survey to help make the service manual better.
=> Add feedback banner

app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Updated cookies and your privacy pages with info about other organisations' cookies and info about social media.
Updated What's new index page and Updates page with details of changes to the 2 pages.
See Jira ticket STAN-1626.
Updating CHANGELOG now.
=> Update 2 policies and updates pages

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Add new entry to A to Z of NHS health writing - approved by clinical team.
CHANGELOG entry - going to do this now.
What's new page updates are in privacy-and-cookies branch along with other recent What's new updates.
=> Add new entry for coronavirus to content style guide

CHANGELOG.md, package-lock.json, package.json
- Install latest version of NHS.UK frontend (3.0.4)
=> install latest version of NHS.UK frontend

CHANGELOG.md, app/views/whats-new/index.njk, app/views/whats-new/show-and-tells.njk, app/views/whats-new/updates.njk
Add new video of our public show and tell on YouTube
Jira STAN-1472
=> Public show and tell on YouTube video

CHANGELOG.md, app/views/index.njk
Updated home page What's new promo to point to March blog post.
JIRA STAN-1382
=> Update promo box on home page

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Add new entry for disease, referring to condition, in A to Z of NHS health writing
Jira STAN-1678
What's new page amended.
Still to add to CHANGELOG.
=> Add reference from disease to condition in A to Z

app.js, app/config.js, package-lock.json, package.json
This code was not having the desired affect due to our traffic manager taking most of the traffic. Thus essentially making it redundant.
=> Remove Azure App Insights code and update dependencies

CHANGELOG.md, app/views/community/backlog-of-components-and-patterns.njk
Updated community backlog page to be in sync with GitHub backlog.
=> Update community backlog

CHANGELOG.md, app/components/checkbox-items-with-hints.njk, app/components/checkboxes-conditional.njk, app/components/radios-conditional.njk, app/scripts/main.js, app/styles/design-example/_design-example.scss, app/views/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form.njk, app/views/design-system/components/checkboxes.njk, app/views/design-system/components/expander.njk, app/views/design-system/components/radios.njk, app/views/design-system/patterns/ask-users-for-their-nhs-number.njk, app/views/includes/design-example-wrapper-full.njk, app/views/includes/design-example-wrapper.njk, app/views/includes/layout.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk, package-lock.json, package.json
Add conditional content for radios and checkboxes.
Also, tidy up the Checkbox items with hints and Checkbox with hint text examples 
(these were labelled up incorrectly and individual item hints were missing).
To do:
=> Conditional content for radios and checkboxes

app/views/includes/design-example-wrapper-full.njk, app/views/includes/design-example-wrapper.njk, app/views/includes/template.njk
use the app JavaScript in templates rather than directly from package
=> use the app JavaScript in templates rather than directly from package

app/views/design-system/components/error-message.njk
Make few stylistic amends to content.
=> Make stylistic amends to content

app/views/design-system/components/footer.njk, app/views/design-system/styles/layout.njk
Update page dates for the footer and layout pages.
=> Update page dates

app/views/design-system/components/error-message.njk
Add info to explain 2 examples.
Does this work @davidhunter08 ?
=> Amend info re legends and labels

CHANGELOG.md, app/components/error-message-in-context.njk, app/components/error-summary-placement-input.njk, app/components/error-summary-placement-multiple.njk, app/components/input-error.njk, app/views/design-system/components/error-message.njk, app/views/design-system/components/error-summary.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk, package-lock.json, package.json
Updating the error message guidance to help users understand how to use them with different components.
- [GitHub issue 222](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/222)
- [Jira - STAN-1684](https://jira.service.nhs.uk/browse/STAN-1684)
=> Update error message guidance

CHANGELOG.md
delete random radios file from the root directory and bump release date for todays release
=> delete random radios file from the root directory and bump date

CHANGELOG.md, app/views/design-system/styles/icons.njk, app/views/includes/design-example.njk, app/views/includes/layout.njk, app/views/includes/scripts.html, package-lock.json, package.json
- use noopener and noreferrer on links that open in new window (https://web.dev/external-anchors-use-rel-noopener/)
- update dependencies to latest versions
- defer the cookie consent to stop the script render blocking the page
=> Security and performance fixes

.eslintrc, package-lock.json, package.json
update dependencies to latest versions
=> update dependencies to latest versions

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/index.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Add entry for NHS Test and Trace to A to Z of NHS health writing
- [N ] CHANGELOG entry - will do this now
- [Y ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry - on index page and updates page
- [Y ] Page updated date
=> Add new entry to A to Z and update what's new section

CHANGELOG.md, app/views/design-system/prototyping.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Added prototype kit how to guides link to the prototyping page.
=> Prototype kit how to guides link

CHANGELOG.md
Add date of release to CHANGELOG
=> populate date for 3.4.0

CHANGELOG.md, package-lock.json, package.json
update dependencies and populate changelog for latest release
=> update dependencies and populate changelog for latest release

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk
Replace "telephone" entry in A to Z with a "phone" entry and link from "telephone and telephone numbers" to "phone and phone numbers"
=> Replace telephone with phone

CHANGELOG.md, app/views/design-system/components/text-input.njk
=> Text input guidance - replace 'telephone' with 'phone'

CHANGELOG.md, README.md, app.js, app/views/accessibility/getting-started.njk, app/views/accessibility/partials/get-in-touch-accessibility.njk, app/views/content/how-to-write-good-questions-for-forms/index.njk, app/views/design-system/components/warning-callout.njk, app/views/design-system/styles/icons.njk, app/views/get-in-touch.njk, app/views/page-not-found.njk, app/views/service-standard/1-understand-users-and-their-needs-context-health-and-care.njk, app/views/service-standard/10-define-what-success-looks-like-and-be-open-about-how-your-service-is-performing.njk, app/views/service-standard/11-choose-the-right-tools-and-technology.njk, app/views/service-standard/12-make-new-source-code-open.njk, app/views/service-standard/15-support-a-culture-of-care.njk, app/views/service-standard/16-make-your-service-clinically-safe.njk, app/views/service-standard/17-make-your-service-interoperable.njk, app/views/service-standard/2-and-3-work-towards-solving-a-whole-problem-and-provide-a-joined-up-experience.njk, app/views/service-standard/4-make-the-service-simple-to-use.njk, app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk, app/views/service-standard/6-create-a-team-that-includes-multidisciplinary-skills-and-perspectives.njk, app/views/service-standard/7-use-agile-ways-of-working.njk, app/views/service-standard/8-iterate-and-improve-frequently.njk, app/views/service-standard/9-respect-and-protect-users-confidentiality-and-privacy.njk, app/views/service-standard/about.njk, package-lock.json, package.json
- create new route to act short URL to join our public Slack instance
- update package dependencies to latest versions
Testing the link on staging before updating the links to our Slack across the NHS digital service manual
=>  create new route to act short URL to join our public Slack instance

CHANGELOG.md
=> populate date for release 3.5.0

CHANGELOG.md, package-lock.json, package.json
Updating dependencies to latest versions and cleaning up the CHANGELOG for the next release
=> update dependencies to latest versions and update changelog

CHANGELOG.md, app.js, package-lock.json, package.json
use Helmet to help secure app by setting various HTTP headers
https://www.npmjs.com/package/helmet
=> use Helmet to help secure app by setting various HTTP headers

CHANGELOG.md, app.js, package-lock.json, package.json
fix an issue with the CSP not executing inline scripts, disabling this in the app will mean we inherit the server/firewall CSP rules.
=>  fix an issue with the CSP not executing inline scripts

app/components/card-basic.njk, app/components/card-clickable.njk, app/components/card-group-half.njk, app/components/card-group-third.njk, app/components/card-heading-level.njk, app/components/card-heading-size.njk, app/components/card-with-image.njk, app/views/content/index.njk, app/views/index.njk, app/views/whats-new/index.njk
Update card component and other cards by removing full stop, as approved by Style Council.
=> Update card component and other cards by removing full stop

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update style guide after Style Council meeting - 2 pages
https://github.com/nhsuk/nhsuk-service-manual/issues/766
=> Amend style guide after Style Council

app/views/design-system/components/card.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update what's new with changes after November Style Council meeting
=> Update what's new

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/design-system/components/images.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update date on images page and add new entry for GUM clinic to A to Z. 
- [Add reference from GUM clinic to sexual health clinic in content style guide #847](https://github.com/nhsuk/nhsuk-service-manual/issues/847)
- [Update image guidance page #727](https://github.com/nhsuk/nhsuk-service-manual/issues/727)
=> Make small changes to 2 pages

CHANGELOG.md, app.js, app/views/content/health-literacy/index.njk, app/views/sitemap.njk
Commented out links to the page and added a redirect.
https://github.com/nhsuk/nhsuk-service-manual/issues/867
=> Hide the 'Use a readability tool to prioritise content' page

CHANGELOG.md, package-lock.json, package.json
Changed version to `3.8.0` and added release date to the `CHANGELOG`.
=> Update version and add date to the CHANGELOG

app/views/content/a-to-z-of-nhs-health-writing.njk
Add links to other parts of content style guide to the A to Z of NHS health writing.
[Add links between the A to Z and other parts of the style guide #866](https://github.com/nhsuk/nhsuk-service-manual/issues/866)
=> Update A to Z with links to other parts of style guide

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/content/numbers-measurements-dates-time.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Change 3 pages with updates after December Style Council meeting.
[Follow up action/publish changes after 9 December Style Council meeting #849](https://github.com/nhsuk/nhsuk-service-manual/issues/849)
=> Update content style guide after Style Council

app/views/content/formatting-and-punctuation.njk
=> Add quotes to make contractions section clearer

CHANGELOG.md, app/components/input-number.njk, app/components/nhs-number-error.njk, app/components/nhs-number-filter-single.njk, app/components/nhs-number-single.njk, app/views/design-system/components/date-input.njk, app/views/design-system/components/text-input.njk, app/views/design-system/patterns/ask-users-for-their-nhs-number.njk, app/views/includes/_header-prototype.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk, package-lock.json, package.json
install nhsuk-frontend v4.1.0 and update components
=> install nhsuk-frontend v4.1.0 and update components

app/views/design-system/components/text-input.njk
=> Add headings and info re decimal numbers

CHANGELOG.md, app/components/input-hint-text.njk, app/components/input-number.njk, app/components/nhs-number-error.njk, app/components/nhs-number-filter-single.njk, app/components/nhs-number-single.njk, package-lock.json, package.json
Remove pattern attribute from NHS number examples
=> Remove pattern attribute from NHS number examples

app/views/whats-new/index.njk
Add note we've updated PDF guidance to What's new index page
=> Update whats-new page

app/views/whats-new/updates.njk
Add note about updated PDF guidance to What's new updates page
=> Update whats-new updates page

CHANGELOG.md
populate the CHANGELOG date for 3.11.0
=> populate the CHANGELOG date for 3.11.0

CHANGELOG.md, app/styles/app/_footer.scss, app/views/includes/_footer.njk, app/views/index.njk, app/views/service-manual-team.njk, app/views/site-map.njk, app/views/sitemap.xml, package-lock.json, package.json
Add a service manual team page.
We want to have an official list we can point to for who is on the team.
=> Service manual team page

app/styles/app/_utilities.scss, app/views/design-system/patterns/reassure-users-that-a-page-is-up-to-date.njk, app/views/includes/app-layout-two-thirds.njk
add alt text and a caption to the review date image
=> add alt text and a caption to the review date image

CHANGELOG.md, app/views/includes/_header-prototype.njk, package-lock.json, package.json
remove role and focusable attributes from the logo
=> remove role and focusable attributes from the logo

CHANGELOG.md, app/views/accessibility/partials/publish-an-accessibility-statement.njk, app/views/accessibility/product-and-delivery.njk, app/views/service-manual-team.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
- Update to this partial: `/accessibility/partials/publish-an-accessibility-statement.njk`
- Update the date at the bottom of this page: `/accessibility/product-and-delivery.njk`
- Update the What's new page and the `whats-new/updates.njk`
- Update to team list on: `app/service-manual-team.njk`
#959 #1038 #1037 #1036 and #1039
=> Update compliance date for accessibility and update to team list #959 #1038 #1037 #1036 #1039

CHANGELOG.md, package-lock.json, package.json
=> Fix release version

azure-pipelines.yml
add [PR triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/bitbucket?view=azure-devops&tabs=yaml#pr-triggers) to Azure pipelines
=> add PR triggers to Azure pipelines

README.md
Notes about our different environments
=> Deployment environments

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/content/health-literacy.njk, app/views/content/how-to-write-good-questions-for-forms/consider-the-sensitivities-around-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/get-the-questions-into-order.njk, app/views/content/how-to-write-good-questions-for-forms/index.njk, app/views/content/how-to-write-good-questions-for-forms/make-sure-you-need-each-question.njk, app/views/content/how-to-write-good-questions-for-forms/test-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/think-of-the-form-as-a-conversation.njk, app/views/content/how-to-write-good-questions-for-forms/understand-the-problem-before-you-write-your-questions.njk, app/views/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users.njk, app/views/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form.njk, app/views/content/how-we-write.njk, app/views/content/inclusive-language.njk, app/views/content/index.njk, app/views/content/links.njk, app/views/content/numbers-measurements-dates-time.njk, app/views/content/pdfs-and-other-non-html-documents.njk, app/views/content/voice-and-tone.njk, app/views/design-system/components/index.njk, app/views/design-system/patterns/index.njk, app/views/design-system/styles/index.njk, app/views/includes/_contact-panel.njk, app/views/includes/app-layout.njk
This is a prototype based on improving the users access to our contribution process through the service manual website
We will use this pull request to review changes, updates et al
#1000 #1001
=> Add contribution links within context #1000 #1001

app/views/content/a-to-z-of-nhs-health-writing.njk
=> Update date at bottom of page

app/views/whats-new/index.njk
Feedback from content designer 2i.
@AdamChrimes , 1 of 3 minor changes.
=> Change reference to style guide

app/views/whats-new/updates.njk
Feedback from content designer 2i.
@AdamChrimes , 2nd of 3 minor changes.
=> Change reference to content style guide

app/views/content/pdfs-and-other-non-html-documents.njk
Update GitHub issue - removed duplicate issue in GitHub
=> Update GitHub issue no

app/views/service-manual-team.njk, package-lock.json
https://github.com/nhsuk/nhsuk-service-manual/issues/1082
=> added Karl and removed Tosin

app/components/error-summary.njk
Over on nhsuk-frontend - the error summary examples have been updated. This pull request simply changes the first example here to match the first one in the readme on nhsuk-frontend.
See https://github.com/nhsuk/nhsuk-frontend/pull/725
=> Bringing main error summary example in line with main example from nhsuk-frontend

CHANGELOG.md, app/views/includes/design-example.njk
Give the design examples HTML, Nunjucks and Copy functionality titles for Adobe analytics
=> Give the design examples HTML, Nunjucks and Copy functionality titles for Adobe analytics

CHANGELOG.md
populate the CHANGELOG release date for 4.0.0
=> populate the CHANGELOG release date for 4.0.0

app/views/service-manual-team.njk
=> Added Indu to the team page

CHANGELOG.md, package-lock.json, package.json
install latest frontend library and update dependencies
=> install latest frontend library and update dependencies

app/views/content/make-content-about-skin-symptoms-more-inclusive.njk, app/views/includes/_side-nav.njk
Create new skin symptoms guidance
Probably needs restructuring. Needs more work tomorrow.
Is it possible to have this in a review environment for now, please?
https://github.com/nhsuk/nhsuk-service-manual/issues/1212
=> Create new skin symptoms page for review

app/views/content/make-content-about-skin-symptoms-more-inclusive.njk
Update backlog number and date
=> Update backlog number and date

app/views/content/a-to-z-of-nhs-health-writing.njk
Update date and delete confusing links to other entries.
=> Update date and delete unnecessary content

app/views/content/inclusive-language.njk
=> Update Page updated date

CHANGELOG.md, package-lock.json, package.json
use correct version for release and populate release date
=> use correct version for release and populate release date

app/views/design-system/components/date-input/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Follow up [PR adding real example to date input component](https://github.com/nhsuk/nhsuk-service-manual/pull/1254).
Update What's new and page date.
=> Update page date and what's new

CHANGELOG.md, package-lock.json, package.json
update dependencies and use correct version for release
=> update dependencies and use correct version for release

app/views/index.njk, app/views/service-standard/15-support-a-culture-of-care.njk, app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk, app/views/service-standard/7-use-agile-ways-of-working.njk, app/views/service-standard/8-iterate-and-improve-frequently.njk, app/views/service-standard/9-respect-and-protect-users-confidentiality-and-privacy.njk, app/views/service-standard/about.njk, app/views/service-standard/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Add info about inclusion and accessibility to service standard 5
=> Define inclusion and accessibility

app/views/whats-new/index.njk
Corrected word "accessibility".
=> Correct typo

README.md
changed link for change log at step 5
=> update step 5 of release steps

azure-pipelines.yml
Adding trigger in build pipeline for IA
=> adding trigger for ia

app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
=> Add survey to What's new

CHANGELOG.md, app/views/service-manual-team.njk
Added myself and removed old team members
=> add myself, remove old team members

app/views/service-manual-team.njk
=> Added Catherine to team page

CHANGELOG.md, app/views/service-manual-team.njk
updated title in reflect end of scheme outcome and updated change log to correct misplacement of team update
=> title change after end of scheme

app/views/service-manual-team.njk
=> Added Dan to team members

app/views/service-manual-team.njk
Replaced hyphen with ampersand for consistency
=> Replaced hyphen with ampersand for consistency

app/views/index.njk
First draft adding the IA guidance to the service manual
=> adding ia guidance

app/views/ia-guidance/about-ia/getting-started-with-ia/index.njk, app/views/ia-guidance/about-ia/how-to-consider-ia-for-your-digital-product/index.njk, app/views/ia-guidance/about-ia/ia-checklist/index.njk, app/views/ia-guidance/about-ia/ia-design-principles/index.njk, app/views/ia-guidance/about-ia/index.njk, app/views/ia-guidance/about-ia/tools-for-ia/index.njk, app/views/ia-guidance/about-ia/what-is-ia/index.njk, app/views/ia-guidance/about-ia/why-ia-is-important/index.njk, app/views/ia-guidance/about-ia/your-topic-in-the-wider-ia/index.njk, app/views/includes/_header-prototype.njk, app/views/includes/_side-nav.njk
Fixed broken nav and added to IA to header
=> Fixed broken nav and added to IA to header

app/views/includes/_side-nav.njk
=> updated nav

CHANGELOG.md, app/views/service-manual-team.njk
update to team members and prepare for release
=> update to team members

app/views/service-manual-team.njk
=> For Sara: Adding Pete to team page

CHANGELOG.md
use the correct year for the release
=> use the correct year for the release

app/views/includes/_side-nav.njk, app/views/information-architecture/about-ia/ia-principles.njk, app/views/information-architecture/about-ia/index.njk, app/views/information-architecture/about-ia/measure-the-success-of-your-ia.njk, app/views/information-architecture/about-ia/why-ia-is-important.njk, app/views/information-architecture/about-ia/your-topic-in-a-wider-website-ia.njk
Iterate content, following Mural board and chat with Brie
=> Make changes as per Mural board

app/views/design-system/patterns/start-page/example/index.njk, app/views/design-system/patterns/start-page/index.njk
Please can you merge into review branch.
=> Iterate start page for review environment

app/views/design-system/patterns/start-page/example/index.njk, app/views/design-system/patterns/start-page/index.njk
Add last round of changes to start page
=> Iterate start page

app/views/service-manual-team.njk
Added the details for myself (Henry Cookson) to the [Service manual team](https://service-manual.nhs.uk/service-manual-team) page.
New starters add themselves to the team page #1446
=> Add Henry Cookson to the Service manual team page

app/views/service-manual-team.njk
Adding myself (Amber) to team page and removing Nancy :(
Issue #1446
=> adding amber to team page and removing nancy

app/views/service-manual-team.njk
=> Added Teodora to team page

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/content/inclusive-language.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Style Council updates - see What's new for details.
=> Do Style Council updates 

app/views/design-system/patterns/start-page/example/index.njk
Cut back example on start page pattern
=> Cut back example

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/design-system/styles/icons/index.njk, app/views/design-system/styles/layout/index.njk, app/views/design-system/styles/page-template/index.njk, app/views/design-system/styles/spacing/index.njk, app/views/design-system/styles/typography/index.njk, app/views/includes/_contact-panel.njk, app/views/includes/_feedback-banner.njk, app/views/includes/_footer.njk, app/views/includes/_header-prototype.njk, app/views/includes/search.njk, package-lock.json, package.json
use correct version number and populate release date
=> use correct version number and populate release date

app/views/design-system/patterns/help-users-get-the-care-they-need/index.njk
Review care card pattern - minor tweaks
https://github.com/nhsuk/nhsuk-service-manual/issues/1366
=> Review care card pattern

app/views/design-system/components/checkboxes/index.njk
Updates guidance and adds a relevant NHS example.
=> Update guidance for "none" option

app/views/design-system/components/checkboxes/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
=> Make minor tweaks.

app/views/design-system/components/checkboxes/hint/index.njk
add missing form wrapper to the checkboxes with hint for semantics
=> add missing form wrapper to the checkboxes with hint

app/views/design-system/patterns/help-users-get-the-care-they-need/index.njk
=> Make a few small changes

app/views/design-system/patterns/help-users-get-the-care-they-need/index.njk
Update content of help-users-get-the-care-they-need index page to match the latest content tweaks made by Sara on the [review-old branch](https://github.com/nhsuk/nhsuk-service-manual/tree/review-old)
=> Small content tweaks to help users get the care they need pattern page

app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/index.njk
Make a content tweak on the "Help users decide when and where to get care (care cards)" pattern page.
=> Make content tweak

app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/index.njk
Iterate content - small changes
=> Make content tweaks after mini-crit

CHANGELOG.md, package-lock.json, package.json
=> updated version and frontend to v6.0.0

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/design-system/patterns/a-to-z-page/default/index.njk, app/views/design-system/patterns/a-to-z-page/navigation/index.njk, app/views/design-system/patterns/a-to-z-page/panel/index.njk, app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/emergency/index.njk, app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/non-urgent/index.njk, app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/two-colons/index.njk, app/views/design-system/patterns/help-users-decide-when-and-where-to-get-care/urgent/index.njk, app/views/includes/layout.njk, package-lock.json, package.json
=> updating navaz and remove list panel

app/views/site-map.njk
=> Fix 2 errors on the sitemap

app/views/accessibility/partials/make-video-and-other-multimedia-content-accessible.njk
Tweak content re subtitles/captions. 
#1308 
#1627
=> Iterate captions content

app/views/content/inclusive-content/skin-symptoms.njk
More iterations on skin symptoms content
- #1575
- #1462
- #1460 
- #1464 
- #1461
=> Iterate skin symptoms content

app/views/content/inclusive-content/_side-nav-mobile.njk, app/views/content/inclusive-content/inclusive-content-principles.njk, app/views/includes/_side-nav.njk
Add inclusive content principles to inclusive content section
#1668
=> Add inclusive content principles

app/views/content/inclusive-content/inclusive-content-principles.njk, app/views/content/inclusive-content/index.njk
=> Tweak index and principles in inclusive content

README.md
Added some documentation, keeping it simple and concise - requires content approval. fixes #1353
=> added gitpod documentation to README

app/views/accessibility/content.njk, app/views/accessibility/design.njk, app/views/accessibility/development.njk, app/views/accessibility/testing.njk, app/views/design-system/styles/colour/index.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
=> Add what's new and page dates

app/views/content/links.njk, app/views/design-system/components/checkboxes/index.njk, app/views/design-system/patterns/ask-users-for-their-nhs-number/index.njk, app/views/service-standard/1-understand-users-and-their-needs-context-health-and-care.njk, app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Make small requested changes.
- #1642 
- #1510 
- #1665 
- [Link to involving people and communities for NHSX #1678](https://github.com/nhsuk/nhsuk-service-manual/issues/1678)
=> Amend links and make small requested changes

app/views/content/links.njk, app/views/design-system/components/checkboxes/index.njk, app/views/design-system/patterns/ask-users-for-their-nhs-number/index.njk, app/views/service-manual-team.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Updated page dates and removed Pete's name from service manual team page
=> Update page dates and team page

azure-pipelines.yml
=> Update build triggers

app/views/content/inclusive-content/inclusive-content-principles.njk
Add link to NHSX guidance from 1st principle
#1678
=> Add link to principles

README.md, azure-pipelines.yml
Updating readme to detail a change to the deploy environments. Also updating the pipelines file to accommodate the new deploy targets
n/a
n/a
=> Details for new environments

app/views/design-system/styles/typography/index.njk
Update text after talking with Michael and Sam.
=> Update text re screen magnifiers

app/views/standards/other-standards/about-technical-policy.njk, app/views/standards/other-standards/authenticate-identity-NHS-login.njk, app/views/standards/other-standards/manage-patient-demographic-data-PDS.njk
Add new About technical policy page and update PDS page
=> Add new page and make minor content changes

app/views/standards-and-technical-policy/index.njk
=> Make minor content changes to hub page

app/views/standards-and-technology/technology/about-technology.njk, app/views/standards-and-technology/technology/authenticate-identity-NHS-login.njk, app/views/standards-and-technology/technology/manage-patient-demographic-data-PDS.njk
Make small content changes to feedback footer and lede text
=> Make small changes to tech pages

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/inclusive-content/ethnicity-religion-and-nationality.njk, app/views/content/inclusive-content/skin-symptoms.njk
=> Iterate skin symptoms

app/views/content/inclusive-content/skin-symptoms.njk
Make a couple of changes requested by MT1.
=> Correct a few words

app/views/content/inclusive-content/skin-symptoms.njk
Few final changes made and captured in screenshot for clinical sign off.
=> Make final changes before clinical sign off

app/views/includes/template.njk
=> Add missing body tag from nunjucks template

app/views/accessibility/content.njk, app/views/accessibility/design.njk, app/views/accessibility/partials/use-alternative-text-for-images-in-content.njk, app/views/accessibility/partials/write-content-thats-easy-to-understand.njk, app/views/accessibility/testing.njk, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/formatting-and-punctuation.njk, app/views/content/how-to-write-good-questions-for-forms/think-of-the-form-as-a-conversation.njk, app/views/content/inclusive-content/age.njk, app/views/content/inclusive-content/disabilities-and-conditions.njk, app/views/content/inclusive-content/ethnicity-religion-and-nationality.njk, app/views/content/inclusive-content/index.njk, app/views/content/inclusive-content/sex-gender-and-sexuality.njk, app/views/content/inclusive-content/skin-symptoms.njk, app/views/content/numbers-measurements-dates-time.njk, app/views/design-system/components/images/index.njk, app/views/service-standard/15-support-a-culture-of-care.njk, app/views/service-standard/5-make-sure-everyone-can-use-the-service.njk, app/views/site-map.njk, app/views/sitemap.xml, app/views/whats-new/updates.njk
Iterate links across the site and make minor changes for consistency across A to Z of health content. 
https://github.com/nhsuk/nhsuk-service-manual/issues/1652
=> Update links across site

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/content/inclusive-content/skin-symptoms.njk, app/views/content/pdfs-and-other-non-html-documents.njk, app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
- Fix inconsistencies
- Finalise What's new
- Do changelog
[](https://github.com/nhsuk/nhsuk-service-manual/issues/1652)
=> Make final amends including changelog

README.md
Remove the pipeline url as requested by Infra/Ops
=> Remove pipeline url

app/views/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update What's new section with info about new tech section
=> Update what's new pages

app/views/content/standard-for-creating-health-content.njk
Amend after crit - approved by Karen (NHSE) too
=> Add amends after content crit

app/views/content/standard-for-creating-health-content.njk
=> Update after feedback

app/views/content/standard-for-creating-health-content.njk
=> Add rural areas

app/views/content/standard-for-creating-health-content.njk
Change "good quality" to "high quality" at request of NHSE and to align with AoMRC.
=> Change good to high quality

CHANGELOG.md, app/views/content/standard-for-creating-health-content.njk
=> Do 2i checks and changelog

CHANGELOG.md, app/views/content/standard-for-creating-health-content.njk, app/views/standards-and-technology/service-standard-points/1-understand-users-and-their-needs-context-health-and-care.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update standard after feedback from DHSC
=> Update standard after feedback

app/views/includes/_contact-panel.njk, app/views/whats-new/index.njk
=> Amend contact panel and alt text

app/views/content/inclusive-content/_side-nav-mobile.njk
Removed space and added dash to link href
=> Hotfix for mobile inclusive content nav

CHANGELOG.md, app/views/content/inclusive-content/_side-nav-mobile.njk, package.json
=> Hotfix skin symptoms mobile link

CHANGELOG.md, app/views/standards-and-technology/service-standard-points/17-make-your-service-interoperable.njk, package.json
=> Remove dead links

CHANGELOG.md, app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/service-manual-team.njk, package.json
=> Make final tweaks including changelog

app/views/design-system/components/expander/index.njk, azure-pipelines.yml
=> Expander - when not to use content update

app/views/design-system/components/back-link/index.njk
Reviewed branch. Added page date December 2022 
[]
(https://github.com/nhsuk/nhsuk-service-manual/issues/1825)
=> Change page date

README.md
Added a line to the README file giving instructions on how to run tests locally
None
=> Added a line about how to run tests locally to README

app/views/whats-new/index.njk, app/views/whats-new/updates.njk
=> Fix What's new index and updates pages

CHANGELOG.md, tests/page-index.spec.js
Additional tests have been added to increase the code coverage stats for this product
No related issue. Just increasing the code coverage stats.
- [ X ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ X ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ X ] CHANGELOG entry
=> Increased unit test coverage in page-index.spec.js

CHANGELOG.md, app/views/design-system/components/buttons/index.njk, app/views/service-manual-team.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
- Make few tweaks to new content on buttons page
- Update service manual team page
- Make few updates to What's new page and CHANGELOB
=> Tweak buttons page and update team page

CHANGELOG.md, app/views/design-system/components/images/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update info re future images guidance - one sentence change
=> Update info re future images guidance

CHANGELOG.md, app/views/design-system/components/back-link/index.njk, app/views/index.njk, app/views/standards-and-technology/service-standard-points/17-make-your-service-interoperable.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Update page dates and What's new for release Jan 2023 (not December 2022)
=> Update dates to Jan 2023

app/views/content/a-to-z-of-nhs-health-writing.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
New style guide entries approved at October Style Council meeting
I'm going to merge another branch into backlink PR and then we can look at merging this one into them.
=> Add entries to A to Z after Style Council meeting

CHANGELOG.md, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Make few tiny changes to What's new files and CHANGELOG.
=> Tweak files where there were conflicts

azure-pipelines.yml, tests/middleware/page-index.test.js
- Rename test file
- Update azure pipeline build configuration for correct code coverage settings.
=> Rename test file. Update SonarQubePrepare configuration

app/views/accessibility/content.njk, app/views/accessibility/design.njk, app/views/accessibility/development.njk, app/views/accessibility/how-to-make-digital-services-accessible.njk, app/views/accessibility/partials/avoid-accessibility-overlays-or-widgets.njk, app/views/accessibility/testing.njk
Make small content changes to accessibility guidance
=> Tweak accessibility guidance

CHANGELOG.md, app/views/accessibility/getting-started.njk, app/views/accessibility/what-all-NHS-services-need-to-do.njk, app/views/design-system/components/character-count/index.njk, app/views/design-system/components/character-count/word-count/index.njk, app/views/design-system/components/tabs/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Make minor changes to accessibility guidance, plus a few to tab and character count pages
=> Make minor changes, mostly re accessibility

CHANGELOG.md, app/views/accessibility/design.njk, app/views/accessibility/development.njk, app/views/accessibility/partials/give-users-time-to-read-and-act.njk, app/views/design-system/components/breadcrumbs/index.njk, app/views/design-system/components/character-count/index.njk, app/views/design-system/components/character-count/without-heading/index.njk, app/views/design-system/components/tabs/index.njk, app/views/whats-new/index.njk, app/views/whats-new/updates.njk
Amend 2 new components pages
Also make some final accessibility tweaks
=> Make final amends after consulting designers

app/views/design-system/components/action-link/default/index.njk
Description
Removed dead link in Action link example. (See https://github.com/nhsuk/nhsuk-frontend/issues/862)
=> Remove dead link

app/styles/main.scss, app/views/design-system/patterns/a-to-z-page/default/index.njk, app/views/design-system/patterns/a-to-z-page/panel/index.njk
Add back to top code to A to Z page pattern
https://github.com/nhsuk/nhsuk-service-manual/issues/1830
=> Add back to top code to A to Z page pattern

app/views/design-system/components/header/default/index.njk, app/views/design-system/components/header/organisational-white-with-nav/index.njk, app/views/design-system/components/header/organisational-white/index.njk, app/views/design-system/components/header/organisational/index.njk, app/views/design-system/components/header/service/index.njk, app/views/design-system/components/header/top-of-page/index.njk
Remove redirect for the search forms in the header variant examples.
Related issue: https://github.com/nhsuk/nhsuk-service-manual/issues/1911
=> Remove search redirect

azure-pipelines.yml
=> Sonarcloud migration

CHANGELOG.md, middleware/file-helper.js
https://nhsd-jira.digital.nhs.uk/browse/TM-2999
=> Slightly changed the regex for less backtracking

CHANGELOG.md, README.md, app/views/content/formatting-and-punctuation.njk, app/views/includes/_side-nav.njk, owasp-suppressions.xml
Remove redundant backlink in content guide
=> Remove back link

.github/PULL_REQUEST_TEMPLATE.md, azure-pipelines.yml
Pipeline is failing the dependancy check.
=> Fix OWASP pipeline issues

app/views/design-system/components/breadcrumbs/default/index.njk, app/views/design-system/patterns/mini-hub/example-symptoms/index.njk, app/views/design-system/patterns/mini-hub/example/index.njk
=> Change example links to use hash

app/views/design-system/components/table/index.njk
This guidance will be looked at again in an upcoming release.
=> Revert guidance for table component

app/views/design-system/components/header/macro-options.json, package-lock.json
Add documentation for adding classes and attributes to primaryLinks within the Header component.
This should only be merged and deployed after https://github.com/nhsuk/nhsuk-frontend/pull/978 has been merged and released.
=> Describe adding primaryLinks classes + attributes

package-lock.json, package.json
=> upgrade eslint

app/views/design-system/components/character-count/index.njk, app/views/design-system/components/index.njk, app/views/design-system/components/summary-list/index.njk, app/views/design-system/components/tabs/index.njk, app/views/design-system/prototyping.njk, app/views/design-system/styles/index.njk
This now has an official NHS URL.
Fixes #2064
=> Update links to prototype kit

app/views/index.njk
Add a user survey link to the homepage. 
Does this need a changelog and/or whats new @sarawilcox ?(I'm thinking no)
Screenshot
=> Add a user survey link to the homepage

package-lock.json, package.json
To be merged before the other open PRs labelled 'Next release'
=> Bump frontend to 9.4.1

app/views/community-and-contribution/community-resources.njk
Have left off changelog and whats new for now, until we know when this will go out.
=> Add NHS app to community resources

app/views/community-and-contribution/community-resources.njk
Add a link to the Jinja port from the NHS service manual website.
=> Add a link to the Jinja port
